### ISSUE TITLE
First Shot Counts / Last Shot Counts buff

### ISSUE THREAD

**Issue by trowl223** [trowl223/Compound_X#108]
_First / Last Shot Counts feats, as written:_
"When reloading, if you Critically succeed, the first round out of that 
magazine deals Extra-Crit damage."
"The last shot in every mag deals Extra-Crit damage, but your reload DC is 
twice as high."

_What this means for players:_
A critical success on reload is not really defined anywhere, but I meant it to be the same range as a weapon hit, 91-100. 10% of the time, a player that reloads will gain +20 damage. A critical success reload is shorter than a normal reload, so most of the time this means that for the cost of a half-action to reload, the player gets +20 damage.

For the second feat, we're looking at a similar low reward / low probability situation, where the +20 damage is buried at the end of the character's magazine. For the majority of weapons, this is a less than 1/10 occurrence, and will occur only at the end of the entire magazine (read: takes a long time to do very little).

_What my edits are:_
"When reloading, if your reload roll is higher than an 80 (including any applicable skills) increase the damage from the first shot by 30. Cannot be used more times in one encounter than the number of appropriate mag slots on the character."
"The last shot in every mag deals +30 damage. Ignore any Crits or Extra-Crits that may occur on this shot."

_Why are these edits beneficial for the game:_
For the first feat, this change will increase the damage capable for the player without enabling a lot of power creep. the phrasing of the second part of the feat is intentional so that a player doesn't have to wait until their magazine is empty (if the feat required an empty-mag-reload), but also restricts the ammount of uses to a sensible amount, effectively each first-round in each magazine on the player has the potential to do +30 damage, but the second round, etc are always treated like normal rounds.
I don't feel that a doubled reload DC is necessitated, it vastly decreases the effectiveness of the feat, crippling the player more than it enhances them.

**Comment by 1sourcecontrol** [comment]
Couple of thoughts:

Why restrict the number of procs per encounter? It adds more stuff for the player to keep track of.
And If a player is spending actions (1 or 2 actions, w/e) on reloading, they are already at a huge disadvantage vs another firing action. If a player reloads-fire-reloads-fires in a turn (without having to aim again), they are nearly halving their DPS. (Exception: this strategy would work well against high armor targets, if your regular gun damage is close to their DR).

Also, either we should restrict these feats from shotguns or heavily consider the possibilities. Since gaining both feats means I get a near-constant +30 damage on double-barrel break-action shotguns w/ high enough reload skill. (which I actually consider to be fair, atm, since those guns have a large firepower disadvantage w/ their reloading time and it would cost 2 feats)

**Comment by bleehu** [comment]
Restricting the the number of procs prevents players from simply reloading every turn reusing the same mags over and over to get that +30 buff on every shot. While the penalty in actions to reload might make the numbers balanced, constantly reloading breaks the aesthetic of the fantasy.

I think it's a great point about shotguns, and we have a similar issue with single-shot weapons. Maybe we should make a note that they don't stack on each other in the event that your mag only has one round in it?

**Comment by 1sourcecontrol** [comment]
>Restricting the the number of procs prevents players from simply reloading every turn reusing the same mags over and over to get that +30 buff on every shot. While the penalty in actions to reload might make the numbers balanced, constantly reloading breaks the aesthetic of the fantasy.

1. I think we can't guarantee aesthetic unless we take extreme measures which would demolish the feat.
What I mean by that is, If I can proc 6 times (because of having 6 unused mags) and it looks advantages to do so every turn or 2x a turn, then I will fire and reload 6 times, ruining the aesthetic. As far as I can see right now, to guarantee the aesthetic we'd have to make the feat only proc'able one time per encounter. Which makes for a real poopy feat in its current state, imo.
I think one implicit thing we may be fighting here is that the feats (at least, as far as I can tell) don't make any sense from a realism perspective. So by their nature, they are fighting the aesthetic. I'm not saying we shouldn't make feats like these, they're great for gameplay; just giving a thought.

1a. The other approach I see to keep the aesthetic by 'soft limits' is to make it a tactically stupid/disadvantageous enough idea to reload all the time. That won't guarantee it, but any smart player probably won't do it. 

1b. Of course we can attempt a combination of both hard and soft limits, but I hope we can come up with something other than another counter to keep track of.

>I think it's a great point about shotguns, and we have a similar issue with single-shot weapons. Maybe we should make a note that they don't stack on each other in the event that your mag only has one round in it?

2. Definitely a possibility. Or even exclude weapons with magazines/capacities smaller than 6.

**Comment by bleehu** [comment]
1) I leave it up to our creative director to make the judgement on aesthetic vs gameplay. @trowl223 
2) I like the "at least 6" fix. I like that a lot.

**Comment by trowl223** [comment]
1. That aesthetic is correct, if you choose to reload 6 times in a row, you've blown through the first round in each of your 6 mags, now you have 6 stale mags to go through.
2. I think these feats should stack in all circumstances except where there is one round. In this case, only First Round Counts should be taken into account. I also don't think these feats should be usable on grenade launchers, rocket launchers or other similar heavy weapons, maybe heavy weapons in general.

**Comment by 1sourcecontrol** [comment]
>2. I think these feats should stack in all circumstances except where there is one round. In this case, only First Round Counts should be taken into account. I also don't think these feats should be usable on grenade launchers, rocket launchers or other similar heavy weapons, maybe heavy weapons in general.

@trowl223 We could put in a clause so that these feats don't affect any AOE, only single target?

**Comment by bleehu** [comment]
I like all of those additions.

**Comment by 1sourcecontrol** [comment]
Ah, I realized later that stale mags keep track of themselves without additional work since players already have to keep track of ammo. Unless the player misses an 80% reload.

Thought: what about the possibility of making the feats just be an extra-crit + 10 damage instead of a pure +30 damage? I know it may be unpopular to say this, but it would allow players to combo these with other feats like doubletap (of course double tap wouldn't work with Last Shot Counts). 

Opinion: I still feel that these feats would be too weak, but I can't give much to support that other than my gut feeling atm.

**Comment by 1sourcecontrol** [comment]
Alright, now that my brain is working better today, I have some more logic to hopefully corroborate my opinion.

Consider a user with a 30 round magazine. For a typical user (crit at 91-100%), every 8 bullets fired gives a ~57% chance of landing at least 1 crit. Firing 30 bullets is a 96% chance of landing at least 1 crit.
 Getting the feat "Never tell me the odds" increases your chance of a crit to 81-100%. Every 4 bullets fired gives a 59% chance of getting at least 1 crit. Every 14 bullets fired gives a 96% chance of getting at least 1 crit.
(Just for the sake of argument, 71-100% crit chance: 2 bullets has a 51% chance of getting at least 1 crit. 9 bullets gives a 96% chance of landing at least 1 crit)

I'm going to try to draw some conclusion from this: it looks like we get roughly double the effective crit chance/performance (if you will) for a given set of bullets for every 10% addition to crit chance. Having the chance to gain +30 damage on the first roll (which may not pan out if you miss that shot) vs a doubled crit chance performance doesn't seem worth the feat (especially since crit procs other benefits in concert with other feats).

_I am making the assumption that the having equal valued feat choices brings greater benefit to the player experience vs unequal value_

**Comment by bleehu** [comment]
It sounds like having the bonus to crit isn't valuable in isolation, but I still like the idea that a clever player (like Stephen) can make a build with crits that is better than the sum of its parts. So long as that build isn't so much better as to break the game. While I agree that this feat isn't really worth it by itself, I don't think that means it should be radically changed from what you're describing.

**Comment by 1sourcecontrol** [comment]
>It sounds like having the bonus to crit isn't valuable in isolation, but I still like the idea that a clever player (like Stephen) can make a build with crits that is better than the sum of its parts. So long as that build isn't so much better as to break the game. While I agree that this feat isn't really worth it by itself, I don't think that means it should be radically changed from what you're describing.

Just to be clear, I'm a proponent of extra-crit+10 damage versus a pure +30 damage.

**Comment by trowl223** [comment]
Can we compromise a little and go for a +15 damage?

**Comment by 1sourcecontrol** [comment]
+15 damage in what context? Does that damage get applied to the last shot of _Last Shot Counts_?

**Comment by trowl223** [comment]
In your recent rebuttal you mentioned treating the buff as +10 Ex-Crit damage, I'd like to test it at +15 Ex-Crit damage.

**Comment by 1sourcecontrol** [comment]
I didn't communicate well, I think. I meant to say, extra-crit damage (20) plus a bonus of +10 for a total of +30 damage. (Which gives the player the pure 30 damage and the possibility of proc'ing other effects from the crit).
But if you want to try it at a total of +35 damage, i'm all for it.

**Comment by trowl223** [comment]
Oh, I must have misunderstood then. No, Extra-Crit + 10 damage is fine : ] Good idea keeping the crit for play with other abilities.

**Comment by bleehu** [comment]
Sounds like we have a consensus then on the rewrites? @trowl223 would you make the branch from dev, make the change and submit the pull request? Or delegate it?

**Comment by trowl223** [comment]
I'll take it.

**Comment by 1sourcecontrol** [comment]
I put it in #144 , i think I covered the feats the way we discussed here, but I allowed these feats to be used with non-AOE heavy weapons.

**Comment by 1sourcecontrol** [comment]
Closing cuz, merged c2.0 into dev #144 and I addressed these there.
