### ISSUE TITLE
Start Reimplementing External Aug

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#112]
In order for us to work efficiently and make a good addition to the game, let's start external augmentation with a well thought-out design document. I recommend putting it in the design guide private repo, so that only developers can see it.

**Comment by 1sourcecontrol** [comment]
I'm not sure what the process is now, after the discussions we've had. 
I've inadvertently made a good segway to add combat frames into the update I'm doing to the armor system, so that's half done. 
(To be clear, the design makes the user have their regular armor with the combat frames, but it's not powered armor; per se. And I believe the user has to be able to use armor with their combat frame, or they will be demolished by any threat)

I haven't touched powered armor.

**Comment by trowl223** [comment]
Lets stick with C-Frames for now since those will be more widely available and need to be balanced for each class. As discussed 28th May, 2017 at our Dev session, the Combat frames will be a separate entity from the Combat Suits -> Powered Armour.

**Comment by 1sourcecontrol** [comment]
Ok, I guess I'll just not attempt any more work on it __edit:__ without more direction.

**Comment by bleehu** [comment]
Tracking work here:
https://github.com/trowl223/Compound_X/projects/1

**Comment by bleehu** [comment]
This is less of an issue, more of a fully-scoped project. It has been documented in the Prioritized Projects document in cxDesign. I'm going to close this ticket for now. When we kick off the Power Armor Project again, I'll make a bunch more small tickets that capture one- or two- sprint chunks of work to actually track progress that can be divided up.
