### ISSUE TITLE
Maluses to min-maxing Characters

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#114]
Personally, if a DM adds an additional debuff to my character, that tangibly changes gameplay because I min-maxed the character, I may feel cheated and I believe that feeling is justified. Debuffing is the DM's call; however, why didn't the game rules say something about min-maxing so the DM doesn't have to trash my strategy? Why do I get the impression that it is an abuse of the system when min-maxing is allowed by the rules? Why am I being penalized for trying to play the game as good as I possibly can?

Steve brought up a good option, there could be maluses for bringing your character below 3 points in a given stat. I think it's a reasonable option, but I don't especially like the aesthetic.
Some techniques limit min-maxing by forcing players to keep their stats within some given range, but I think some degree of min-maxing allows characters/players to get the most out of the game. And if the characters are forced to be in some smaller range, why does a wider range even exist?

Also, specific example, if I give significant maluses for putting a 1 in perception, then taking the feat _Hands of an Artist_ is not as great. (And if it is not great enough, to the point of mediocrity, then what's the point of the feat's existance?)

 I know there are many ways to handle this issue, but at the moment, I don't see any one way as the perfect answer.
Thoughts?

**Comment by trowl223** [comment]
Here are my opinions, and later, some guidelines:

Opinion: Min maxing is beneficial to character diversity, and yes, allows for greater exploration of what is possible in the game. If we wanted to perfectly balance the game, we'd remove stats all-together and use a purely skill-based system. There are systems that do this, and they work well for the asthetic they are trying to present. There is a reason that I intentionally used a point-buy system, and that reason is it gives another illusion to the player of diversity. Not an illusion in the sense that it does nothing, but an illusion in the sense that the player _feels_ that they are creating something visibly different from other players by getting to choose their character's traits, thus more mechanically defining who their character is.

Guideline: Maluses should be put into place for each stat in order to give reason for a hard limit at 1 as a minimum.
    STR =1: Cannot impart force on other objects. Cannot interact with the environment in a physical way. Examples given: cannot use doors, carry equipment, wear anything beyond a light tunic, cannot run, jump or climb.
    PER =1: Functionally blind.
    FORT =1: Sickly to the point of debilitation. moderate changes of environment render the character immobile. Any force imparted on the character create bruises, break bones, etc.
    CHA =1: Cannot communicate. A CHA of 2 will allow the character to communicate in the most basic forms. Hand signs or mono-syllabic expression of ideas.
    INT =1: Cannot think or interpret things. The character would completely rely on the orders of their comrades for even the most mundane tasks, and cannot accomplish complex tasks such as "Put out that fire", you would need to specify "grab that bucket" "fill the bucket with water", "pour the water onto that fire" as separate instructions. If you think about it mechanically, an INT of 1 allows for 2 skills points per level, so the character would gain a skill every 5 levels. I would say at an INT of one they should also only start with 1 or 2 skills at a level 10 rather than 5.
    DEX =1: Clumsy in everything, difficulty moving to the point of taking damage from tripping over things and dropping items on themselves. Often.
    LUK =1: Ever see those old cartoons of people walking under ladders and having pianos / anvils narrowly miss them? They might not miss for characters with a Luck of 1. And there would be lots of such precariously placed items. Also weapon jams, anti-crits, etc.

**Comment by 1sourcecontrol** [comment]
Ok, sounds like a plan.. But, can you define the debilitations to be more practical/numerical?
I.e., STR = 1, does this mean I can't shoot a gun, or engage in combat at all? Am I only useful as a charisma player? If I can't run, what is my max move speed?
PER = 1, what does it mean to be functionally blind? Can I shoot a weapon with -16% accuracy like the rules say?
FORT = 1, do I take double damage from status effects?
etc.

The reason I ask for more exact definitions is so that the player will have some numbers to compare so that they can understand what they are losing/gaining by min-maxing. And also so that a DM doesn't have to make up harsher rules than necessary, to fill in the missing stats.

**Comment by trowl223** [comment]
STR: I should revise that to say that the player has just enough strength to support themselves and light clothing. They have no carry capacity. Max movement is 2m unless they have Dex of 1.
PER: No, they would have no way to perceive their environment at all. They may have a rudimentary speech assist plugin that translates incoming speech into basic emotions, but it wouldn't be very capable for complex instructions. Stats are linked since human functions require the interaction of multiple skills. A totally blind player cannot use the search or awareness skills and takes a -20 to speech rolls. They also can't navigate without the use of some aid, like a white cane.
FORT: Double damage from status effects would be pretty hefty. For now lets say they can't deal lethal unarmed damage, and their non-lethal unarmed damage is halved. In addition, for whatever damage they deal, they take half for unarmed / armed melee combat. That, combined with a severely crippled health pool should do for now.
CHA: -50 on Speech, Deceive etc. skills. Players with CHA of 1 must make a speech check whenever attempting to communicate an idea to a friendly player. Under normal circumstances, the DC to communicate a 1 sentence simple idea is 20. in combat this DC increases to 30. Communication in combat counts as 1 Action.
INT: Durring character creation, instead of choosing 5 skills each starting with 10 points, the player may choose 2 skills. The character is reliant on instructions from other characters, and takes a -20 on all skill checks they do not have proficiency in -> **"Having proficiency" should be defined in Core Rules under the "Using a Skill" section as the following: 'A character has Proficiency in a skill when they have 10 or more points in the skill.'**
DEX: The player cannot take any skills which use Dexterity as their base stat. Maybe this should be applied to all Stats that have only 1 point, but for now since I can't think of anything else numerical for DEX we'll leave it just here. Obviously the character will be taking penalites left and right to anything that is based in Dex and their movement speed is 1, so they already aren't well off.
LUK: The jam range for all weapons increases by 20. for melee users, they increase their crit chance by 10 per field (91 -> 101, 96 -> 106) essentially removing their ability to score a Critical Hit, unless their crit ranges are influenced by a feat or class ability.

Please offer any suggestions, these are just my ideas for now.

**Comment by bleehu** [comment]
That luck penalty only affects classes that work with guns. We need to add a penalty that costs something from mage/sorceror/monk as well.

**Comment by trowl223** [comment]
"For melee users, they increase their crit chance by 10 per field (91 -> 101, 96 -> 106) essentially removing their ability to score a Critical Hit, unless their crit ranges are influenced by a feat or class ability."

**Comment by bleehu** [comment]
it seems to me that losing the ability to melee crit is a minimal loss compared to what could be gained. For instance, if I was a melee assassin, I would totally drop Luck for Dex, fort and strength. If I can't crit with melee, no problem; I'll be doing at least 80 damage ignoring armor per hit anyway. 

What if instead of messing with their jam range and crit chance passively, what if we create a "black cat table" that must be rolled on at the beginning of combat by any character that has a Luck of 1. Something like:

1. Your weapon malfunctions and cannot be used until it is repaired
2. You cannot get crits this battle
3. something bad
4. you trip and twist your ankle, take 15 damage
5. nothing bad happens... this time.
6. nothing bad happens... this time.

**Comment by trowl223** [comment]
I like that. We could even make the table listed from -30 to 100. Players with 5 luck will be subject to almost no bad luck, but players at 1 and 2 will have a sufficient negative modifier to fall into bad luck most of the time. Players don't normally have to roll for this table unless certain conditions are met, but players with a luck of 1 always roll from it at the start of combat.

**Comment by bleehu** [comment]
Would things above 50 be good in the "large" table of -30-100? Or would it still be the "Black Cat" table?

**Comment by 1sourcecontrol** [comment]
Alright, this is very productive!

> PER: No, they would have no way to perceive their environment at all. 

  So does that or does that not remove the players ability to fight at all in combat?

My caution when designing this is:
While it may be reasonable to say someone in the real world wouldn't be able to fight by having a 1 in a primary stat, if we take away a player's ability to make meaningful contributions to half of the game's gameplay, that basically forces players to never put a 1 in the stat. Or they should bring a good book to any CX campaign so they will have something to do 👎 . So I suggest penalties should be strong but not game ruining for the player (which, I think you guys are doing pretty well already; I just want to make our design goals clear).
1. A 1 str player could potentially still use magic, so they'd be forced to use magic or not contribute to fighting in the early game, so maybe that's ok?

**Comment by trowl223** [comment]
@bleehu They would be more neutral things, with maybe a roll between 90-100 granting a very small bonus, or maybe 80-100?

@1sourcecontrol I guess that's true. What I'm trying to say is if 1 is the lowest score the character can have and still be slightly useful, then a 0 would be the score where you are 100% functionally blind. Have I fallen into this same trap with any of the other proposed penalties for other stats??

**Comment by bleehu** [comment]
I believe the question label has been answered and we are resolved to move forward by adding to the basic rules a series of penalties as trowl223 described above. I would like to drop the question and help wanted labels and replace them with a greenlight - awaiting pull request label. @1sourcecontrol would you mind grabbing this and doing the work to enter it?

**Comment by 1sourcecontrol** [comment]
@trowl223, no I think it's fine. We'll just have to watch how STR And PER are implemented to avoid uselessness.

@bleehu sure, I'll take it.

Is it all right if I just make a simpler black cat table, or do we want the larger table?

**Comment by bleehu** [comment]
Personally, I would keep it simple. But if you're taking the work, you get to decide!

**Comment by bleehu** [comment]
PR #119 merged. Closing issue.
