### ISSUE TITLE
Level 10 weapons in play unplayable

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#123]
There's dev notes and general mess all over the level 10 weapons. We need to clean it up so that it's playable. This work needs to be prioritized! We're going to play this soon!

**Comment by trowl223** [comment]
I'll take a look at it, but i'll need to work with @1sourcecontrol to translate the old weapon stats into the new system.

**Comment by bleehu** [comment]
We need to keep 1source focused on shipping Combat2.0 because it's blocking the generation of other content. I'd like to see that finished by Sprint C with the comments/tweaks wrapping up in Sprint D. (As of this writing we're in Sprint B)

**Comment by 1sourcecontrol** [comment]
After C2.0 & powered armor are in, I can take this on

**Comment by bleehu** [comment]
If we're slating this to be after PA, it'll get done a few months after we're trying to play with it. I'll have to allocate Turtle and/or Shrub to it if we can get him on board.

**Comment by 1sourcecontrol** [comment]
Alright. They'll have to work closely with me to get it done, then.
I'd need to write a small manual to show how to do all the calculations, but I can just do them if -whoever- does all the other work. Since I may not have the time for a manual. And I'd need to clean up my Excel a bit.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by trowl223** [comment]
I'll try to begin implementations. @1sourcecontrol do you have a function for moving old stats over to the new system, or should I go by feel to fit the current trends?

**Comment by 1sourcecontrol** [comment]
I don't have a written step-by-step function, so to speak. In order to get the cost values, I have to clean up my excel a lot and write down how to use it. There's quite a few steps.

But I do have a few guidelines for keeping with the feel of the current weapons if you want to start translating without the excel equations. I'm not able to write them down right now because I have to get back to work.

**Comment by bleehu** [comment]
Fixed when we merge combat 2.0 https://github.com/bleehu/Compound_X/commit/d2061451041d0e0caf3b47ac4f0835bb75f0d12c
