### ISSUE TITLE
Level 10 weapon attachments missing

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#126]
We don't have any level 10 slings at all.

**Comment by trowl223** [comment]
Its tough to really come up with a sling better than what exists, other than generic sling #s 3 & 4 which have slightly better stats. I think thats what we'll need to go with though.
I do like the idea of a sling with a magnetic attachment point that is quicker than the traditional clip system used on a 1 point or 2 point sling.

**Comment by bleehu** [comment]
If we just use better numbers, then we need to scale the level 10 enemies appropriately. I think that's the correct solution, but that's going to break your earlier edict that level 1 players be dangerous to level 10 enemies and vice versa.

**Comment by 1sourcecontrol** [comment]
Here's a few ideas, magnetic slings that auto-attach to a weapon you are holding. Allowing you to swap the sling for a rifle or a pistol. Slings that help with ammo reloading. Slings that actually carry ammo. Slings that  hold medi-gel or something. Slings that are usable like det-cord or other expendable items

**Comment by trowl223** [comment]
@bleehu That's true. I think the main part of my vision is that players should never lose sight of the fact that they are very mortal. Something like increasing the stats on player gear should actually occur and that does mean that level appropriate encounters should have an appropriately scaled threat level. I may be reversing my opinion a little here, but its just like you stressed to players in your sandbox campaign. Sure, you can try to take on a tougher mission, and with lots of lucky rolls and exquisite teamwork, it may be possible; but it is certainly inadvisable. 

Interesting ideas @1sourcecontrol! I'd like to try to implement the Magnetic multi-sling, 

What if we let go of the idea of level 10 attachments and just had many attachments and all attachments are priced a little higher, so that it is harder for players to obtain many attachments at early levels. That way weapon enhancements are valued a little more highly in order to place a little more stress on the importance of speccing your weapon to suit your needs?

**Comment by 1sourcecontrol** [comment]
I think there's good argument for either side. We could just split up the attachments more by level than they already are. Do a level requirement 1,5,10,20 scheme like i'm doing with the weapons. Then we don't have to build a completely new set of attachments for level 10. 
It might be a lot easier to build new attachments if we changed designs and made them less piecemeal and sold them as sets. For example:
Having a max of 2/3 attachments per weapon. Each attachment is like a set
> "ECSC rifle front-end replacement for automatic weapons": 'comes with a heavy barrel with a rail and foregrip section. -10% miss chance when firing in automatic, +5m range, -5 reflex' 

It would be easy just to change brands and/or change the name a little bit and modify a stat or add another stat for a new attachment set.
idk, just a thought

**Comment by bleehu** [comment]
Price gating is more elegant, and adds to the immersion better. But it's a lot harder to develop with because we have to keep a very close eye on how players accumulate wealth. 
Level gating makes development and balancing easier (read: faster) because we don't have to worry about someone getting a really cool attachment too early. 

My vote is level gating because our dev group likes to make new things and lots of them. We get to do more of that quicker with that option without incurring a nasty tech debt to clean up later. That said, I'd be very happy with either method.

**Comment by trowl223** [comment]
I agree with @bleehu, and I'd prefer a system that allows users to kit out their weapons per item. It might be a good idea to have example loadouts just like having an example class with picked stats and skills so that players who just want to jump in can have an example of what can be effective.

**Comment by bleehu** [comment]
I really like that example loadout idea. We should make that happen.

**Comment by bleehu** [comment]
Level 10 weapon attachments were added in combat 2.0
