### ISSUE TITLE
Schroder R-130 doesn't have suppressing fire label?

### ISSUE THREAD

**Issue by Michael-Hedges** [trowl223/Compound_X#13]
is its effect on top of suppressing fire or in place of it or what?
What does the suppressing fire label _do_ anyway?

**Comment by trowl223** [comment]
Since there's no Supporting Fire label it doesn't have that effect, it has its own unique effect, which is outlined. Supporting Fire is documented in the place that gun effects are explained, in the weapons document:
"Supporting Fire: On Hit, target is forced to take cover for one action, stackable, unless they pass a 70% FORT or INT check. If they pass the check, they negate the cover, but take an additional shot. Additionally, targets affected by supporting fire cannot make a reflex shot against anyone leaving cover."
The way the R-130 is written, any time the gun is fired, the targets must pass the saving throw to move or to fire. This differs from Supporting Fire in that on a successful passing of the saving throw, the targets may move out for with out taking an extra hit penalty, but the DC is higher.

**Comment by trowl223** [comment]
*Targets may move or fire without
