### ISSUE TITLE
Death saving throws are a house rule

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#133]
Without some bleedout system, there's no actual danger from going down. We should make the death saving throws part of the core rules. If we don't do that or implement a similar system, then we'll suffer the cockroach effect.

**Comment by trowl223** [comment]
I'm going to quote out of D&D 5e because I like the way they handle health points being reduced to 0.

As taken from Roll20.net:

> Death Saving Throws
> Whenever you start your turn with 0 hit points, you must make a Special saving throw, called a death saving throw, to determine whether you creep closer to death or hang onto life. Unlike other saving throws, this one isn’t tied to any ability score. You are in the hands of fate now, aided only by Spells and features that improve your chances of succeeding on a saving throw.
> Roll a d20: If the roll is 10 or higher, you succeed. Otherwise, you fail. A success or failure has no effect by itself. On your third success, you become stable (see below). On your third failure, you die. The successes and failures don’t need to be consecutive; keep track of both until you collect three of a kind. The number of both is reset to zero when you regain any hit points or become stable.

https://roll20.net/compendium/dnd5e/Combat#content, D&D Fifth Edition Compendium, Wizards of the Coast, LLC.

The system I like best for Compound_X is the following:
When you have 0 Hit Points, your Actions per Turn are reduced to 0 and you must make a Death Saving Throw once per turn. The maximum number of saving throws you can make per turn is half your usual Action allowance, rounding down (4 for most players, I don't think we've added the ability to increase the number of Actions per Turn yet, have we? I'd like that to be a thing with certain aspects, like having auto-firing mounts on Combat-Frames, for example. I digress . . .) The DC for this saving throw is equal to 70 - any bonuses to their Knock-out Threshold, including any buffs to this stat by any abilities or effects (Gives us room for some spells and abilities here). Any Cyborgs with Internal Reinforcing, for example, would have a DC of 65 since their K-oT is increased by 5.
On success, the player becomes conscious. The player has a number of chances to succeed equal to the average of their 3 physical stats (Fortitude, Strength and Dexterity), rounding down. Once all chances have been consumed, the player is evicted, so to speak.
The chances are replenished once the player is able to take a number of long rests equal to 10 - the average of their mental stats (Perception, Charisma and Inteligence), rounding up. This period resets whenever the player has to make a Death Saving Throw in combat.

The differences between my proposed system and the one used in D&D 5e, a relatively well balanced game, as I perceive them, are the following:

The advantages to using my proposed system over the one used in D&D 5e, a relatively well balanced game, are the following:
- The player has a larger action allowance and needs only make 1 successful save. This supports our concept that combat should have a rapid pace by allowing the player to return into combat more quickly.
- The player has a limited amount of times they can be grievously knocked down. We want the game to feel more lethal to the player, so having an unlimited number of saves per combat does not work in our favor. Here we are able to have mid-term control on the player's pacing by discouraging them from making too many risky moves in combat. We want them to play smart.
- The DC is flexible but starts at a respectful level that informs the player on the severity of their situation. This enhances the idea for the player that death is a big deal, and being in this position is something that is against the player's odds.
- The player is able to regenerate these saving throws, which does two important things:
1. We are able to teach the player a lesson as they learn combat, by slowly taking away their option of making risky moves as they are knocked down.
2. The fact that the reset period is lengthened when the player gets in a tight spot is a lot closer to having a static pool for players, as it does the same thing in the case where a player is repeatedly knocked down. Eventually as players continue to rely on their Death Saving Throw chances, they will run out. Here we reward the players who think before moving and stay on their feet more often by providing them with more of a cushion. If we like this system, we could even adjust the relative difficulty for whole campaigns by sliding the reset tolerance up. Maybe a player can use 1 or 2 more saving throws while in their reset period before the period is lengthened. Or maybe we set that slider to 0, as you propose in your campaign. But having a variable that is GM controlled gives the GM a clear way of affecting the overall difficulty in their campaign other than relying on adjusting the challenge level of every single combat.
- This also plays into the inclusion of both physical and mental stats in this system. It gives players two options that they can build when thinking about  Death Saving Throws: they can give more points to physical stats in order to enhance their overall cushion, or they can put more points into mental stats in order to increase their refresh rate.

I'd really like us to look at a system like this, what do you guys think?

**Comment by 1sourcecontrol** [comment]
Sounds like the system has a lot of potential. Some thoughts:

> This supports our concept that combat should have a rapid pace by allowing the player to return into combat more quickly.

Or die much more quickly, w/ twice as many death throws per turn and a low 30% chance of success at the start of the campaign.

>Once all chances have been consumed, the player is evicted, so to speak.

 Is it character perma-dead like you implied or do you mean something else?

> (Fortitude, Strength and Dexterity)... (Perception, Charisma and Inteligence)...

I suggest caution here. Luck already has problems; devaluing Luck more will (potentially) make the primary stats even harder to balance.  (Luck being devalued because it is not a part of the saving throw system).

**Comment by bleehu** [comment]
Maybe I'm misunderstanding. When they make a successful save they get back up themselves? Or are they still down, just not bleeding out?

**Comment by trowl223** [comment]
@1sourcecontrol : 1. We can see about adjusting that DC, maybe make it 50 + Character level?
2. They are Dead. I won't use the term "Perma-dead", any good fantasy setting has . . . loopholes.
3. Thats very true. Maybe we can take those averages and shift the end result by adding Luck?

@bleehu They are conscious, but not up. They'll still need healing from their wounds. Maybe a clause could be added at the end that outlines the condition the player is in when they return to consciousness:

"On a successful save, the player returns to consciousness. The player will be at 5 health points and will need to be healed back to 50 points or more in order to be back in fighting shape."

Is this sufficient?

**Comment by 1sourcecontrol** [comment]
1. Sounds pretty good.
2.
3. What about having the consciousnesses DC be 70 - 2 x Luck?
      Let's be aware that this is a good opportunity to re-balance the primary stats. Ideally Charisma and Luck could also be heavily considered for emphasis. In terms of realism, Charisma could likely have a heavy effect on a characters desire/will to survive when they are perishing. Regaining consciousness would be quite a true Luck effect, considering all the possibilities of how the character got unconscious in the first place.

>"On a successful save, the player returns to consciousness. The player will be at 5 health points and will need to be healed back to 50 points or more in order to be back in fighting shape."

Does this mean the player won't be able to do anything until healed to 50 points? It sounds quite contrary to what you said previously: 

> ...combat should have a rapid pace by allowing the player to return into combat more quickly.

What if the player regains consciousness  and they are fully functional except for 5 h.p., half-movement speed, and two turns to get some kind of first aid or they go unconscious again?

**Comment by bleehu** [comment]
1. DC = 50 + Character level implies your chance to bleed out *increases* as you level? Or did you mean that the Roll is given a bonus of Character Level? I could see a good argument either way; as your character level increases, the player gets more experienced and should need a higher difficulty curve to stay engaged. (That assumes a player's first character). On the other hand, the longer a character lives, the more attached everyone gets to them, so the harder it should be to end their story?

2. Not every good fantasy world has "loopholes". Furthermore the loopholes aren't what make the fantasy world good. There's no drama in Frodo being stabbed by the wraith blade if he's just going to get a "loophole" later like Gandalf. Sacrificing Kaiden Alenko for the mission means nothing if you know you're going to have the option to stitch him back together like Shepard. Part of what makes resurrection meaningful is that it breaks the rule. But in order for it to be meaningful, there has to be the permadeath rule there to break. And that rule has to be followed more often than not, otherwise Barbosa is gonna call it "More of a guideline". What made the cloning vats cool was that it was a reveal. Who are you going to make that reveal to now? Even with house ruled, perma-death, bleedout without consciousness at the end **only two characters have ever died**. And the players got pissed for all of about an hour before starting to play again. 
The drama that is created when one teammate is on that slippery slope to infinity and the others are going to risk it all to save them are the stories that get told between games. We still talk about that time Rodger dove off of the space station to catch Kensington. The group talks about the time Kensington dropped to 5 health to save Qunioa from floating to space, and Qunioa fought off the breacher to stop Kensington from bleeding out. The harder we make it to die, the less picking up a friend means, and the less the risk to pick up that friend up means. It wrecks that engagement on two fronts. 
Even furthermore, the threat of (perma)death is really important for role playing. We were having some problems with players who wanted to be showstoppers, wanted to be the star of the show. They treated each other as sidekicks. But they had each saved each other's lives. It was really simple for me to say, "listen, this roleplaying isn't realistic. You don't talk down to someone who put your intestines back in you last week. You're costars." And it worked like a charm. The characters still have their differences, but they work together in spite of those differences because of the high stakes of their history together. Imagine if those players just roll high enough to stabilize and then give themselves a medpack after the battle? We'd lose all of that. 
Way furthermore, there are already in-game mitigations to players dying. That's why so few of them have died yet.
https://github.com/trowl223/Compound_X/blob/play/play/PlayerRules/CharacterCreation/Class-Specific%20Documentation/Medic%20Proceedures.txt#L381
Most players haven't connected the dots yet, because I very quietly added it to the design and left it to the players who enjoy exploring game mechanics (we have a few of those kinds of players) to develop their strats and tactics. When we have a level 10 player die, suddenly we'll see this come up. 
3. As a corollary to the reasons listed above, don't offer stabilize. Instead, allow the Fortitude stat to give players a longer bleedout time than proposed in DnD. One of the differences in design between DnD and our game that lets us get away with this is our focus on ranged combat. In most CX encounters, there aren't goblins with swords and shields standing between you and your downed friend. You can just go running through the gunfire to get to them before they bleed out. This is an oversimplification, but the dynamic is still there.

**Comment by trowl223** [comment]
@1sourcecontrol 
I like the consciousnesses DC being set to 70 - (2 x Luck), that seems like it could be a good way to include luck.

You're right, that is a little contradictory. We should just give them fully functionality and 5 HP. If they want to go running into waiting death again, that's on them.

@bleehu 
I may have meant to say 50-Level, would equate to 50 and add Level to your roll. As the character levels, they should become stronger.
You're right. We'll rule that once a character runs out of death saving throws, they're dead, 0 pulse no respiration.
I like that idea, maybe we can try that out. How would the mechanic work then?

**Comment by 1sourcecontrol** [comment]
Thinking, reading, and discussing a lot more about this, I feel like non-stabilizing slow-or-no replenishment death throws offer the most fun, realism, gritty'ness and excitement for compound X.

1. Non-stabilizing increases the teamwork required, the cost of repeated dumb decisions, the cost of abusing the game by doing unrealistic things, and the anticipation and excitement of daring moves and/or last second saves.

2. Having the death throws determined half by the 'brain' stats and half by the 'brawn' stats is probably unnecessary because players will almost certainly invest in both sides because of more significant reasons. 
In other words, I think the most likely possibility is that the categories are so broad as to almost make them meaningless: 
If I am a regular shooter, perception is super important, dex is important or I fail at fire an maneuver, some fort is a must because of instant death by luck, int is important or I can't reload as reliably or do any basic tasks, I absolutely have to have some strength or I can't use a ranged weapon. So now I'm left with some choices on what to focus stat points more on, but a lot of it is decided for me if I want to reasonably accomplish my goal.

Another possibility I see is that investing in brawn becomes so much better than brains that it skews the player's builds towards brawn. Having 10+ Fort and tons of other brawn will make you almost impossible to permanently kill for any somewhat competent player with tons of fort saves.

I think it's a good idea to consider giving the player the option to buy saving throws through medical assistance; this gives another valuable choice to the player throughout the game.

**Comment by 1sourcecontrol** [comment]
@bleehu, can you make a reply to Taylor's comment, above? And maybe mine as well?

**Comment by bleehu** [comment]
Having meditated on it whilst stuck in traffic on several occasions, reading things here and discussing it with Alex over text. I realize this is way more complicated than I originally thought. I think we can do better than my house rule of Fort number of saves before you're gone, but I still hold that permadeath is worth the added punishment for failure. 
Ultimately, the final decision should be Trowl's. I would like to write up an addendum to the basic rules and submit it as a proposal. I think until we have specific language to point to, we are going to pontificate in circles at varying levels of vagueness, abstractness and philosophize without getting anything done. 
Is there anything more specific you'd like me to weigh in on?

**Comment by 1sourcecontrol** [comment]
I just wanted to see what you think of our comments, as we wait for @trowl223 to respond.

I'm all for a formal proposal. Whatever works!

**Comment by trowl223** [comment]
When your character falls below 1 hit point, you get 3 saving throws. These throws are not tied to any attribute. When you fail any three times (50/50?), you die. You can only be brought back by a teammate's assistance. Once you have used a saving throw, the next time you fall below 1 health points your saving throws fall to 2. the next time, you have 1. you can only replenish these saving throws by going a whole encounter without having to use any. After doing so, you jump up one level.

**Comment by bleehu** [comment]
Doing some work on this, I found that in order to add this rule, I need to yank the existing one. Otherwise We'll have it defined differently in two places. 

Out of curiosity, I decided to check when this particular rule was actually added.

Turns out, Trowl223 added this back in 2016. I don't think death was ever a house rule...
https://github.com/trowl223/Compound_X/commit/ff665dea28500c1229de99a0b18549eed9b8f926#diff-c344212ea09816d3d560085d0766c0b7R325
