### ISSUE TITLE
gripe list 11/24/16

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#15]
leveling class feats every 3 levels? -- see scoundrel
some feats left unfinished
counter spell still in
cover slide op as hell, does not say you cant end up next to an enemy/player...
archon is pushed, useable?
2 external augmentation files in character creation
armor in demage_redux file still have ep listed
casters are pushed, spells not complete
nanite costs for paladins are too high.with 10 int and both upgrade feats, you have 150+30 assuming average is taken. 
	that is 180 nanites, how are paladins supposed to cast the 200 cost spells? not to mention this is assuming min maxing int and charisma
	to be able to buy those prayers in the first place. thus gutting the character's other stats. also it allows the character to only cast that one
	spell the entire encounter, yes you can get the prayer that regens nanites, but it is 2 actions for 40 nanites that is 5 full turns sitting in one place to cast again...
	atleast make it comparable to warlocks...

**Comment by trowl223** [comment]
Please make separate issues for each item in the future.


Scoundrel removed from play. It was commented out, but comments don't show up highlighted on github. Scoundrel has never been a class and remains a work in progress / shelved indefinitely.
It would help to list specific feats. The only two i see are "With friends like these ..." and "...Who needs nanotechnologies" which are intentionally left undescribed, as their effects are a surprise to those that want to pursue them. If you look at the classes involved that may give a hint at the content, but thats all I'll say there :P
I was not aware counter-spell was to be removed, are you privy to information there? We are currently re-working magic, but in the mean-time counters-pell is one of the only defenses a player may have against magic. Think of it as armour against magic.
I had talked to mike about coverslide and combat roll, I removed them for now until a fix is patched.
Ex.Aug fixed, the old one with reference to EP has been deleted.
Damage redux is not the file to look at for armour, The document you are looking for is "5. Armour List.txt"
Still working on Tome of Spells, my bad. I didn't want to completely remove magic classes for the duration of the fix, so the incomplete list is there for anyone who wants to try to piece together a mage or sorcerer for now.

On Paladin spell / prayer cost:
Spells are you normal attacks and augments which enhance the group or player. Prayers are meant to be once per encounter type abilities. Additionally, C_X is balanced so that each point of accuracy, health, damage, nanite, etc. is equivalent to each other. A heal spell which grants 90 health and heals a wound is going to cost 90+ nanites. Similarly, an ability which drains 100 nanites from all characters nearby (restoring what you spent on the spell in the process and then some . . .)  while by the same token denying enemies the ability to use magic or other nanite-based abilities is devastating. You also forgot in your calculation that every few levels the player gets a bonus to one stat, so this spell probably wouldn't see use until level 15 or higher, when this sort of drastic ability might be necessary to stop some powerful caster from raining hell on the party.
Paladins are powerful beyond spells though. They also have higher starting cash than most classes and access to automatic rifles, long rifles, and heavy armour, making them one of the tankier classes in terms of conventional weapons alone. Giving them easier access to tide-shifting spells will most-likely break the class, leading to the current level of balance.
I would love to hear your thoughts on this analysis, as I haven't played a modern paladin beyond battle simulations. I'd also like to note that previously everyone was saying that magic classes were overpowered. To me the Paladin is a class balanced in martial and arcane ability. They can't be complete powerhouses in both.
