### ISSUE TITLE
Engineer Skill Tree Structural Concerns

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#165]
Most notably, I would like to point out that it's a little punishing as-is to make an engineer without the rest of the party being robots. The repair tree, which is the resource generator tree, has an enormous reliance on skills that can only target cybernetic allies. Below is a fully enumerated list of skills in the repair trees that do *not* require a cybernetic ally target (note that most of them are still gated behind a skill that does require such a target)

Restore Armor - Cyberphysical - gated behind 1 cyber only (Reboot)
Percussive Maintenance - Cyberphysical - gated behind 2 cyber only (Reboot & Data Scrub)

Duct Tape - Material
Weapon Tuning - Material
Vehicle Repair - Material
Engine Tuning - Material - Gated behind 1 cyber only (Micro-assembler)
Zero Friction Covalent - Material - Gated behind 1 cyber only (Micro-assembler)
Sup it Up - Material - Gated behind 1 cyber only (Micro-assembler)

Repulsor Recharge - Optronic
Repulsor Overcharge - Optronic - Gated behind 1 cyber only
Repulsor Projection - Optronic - Gated behind 1-2 cyber only
Refractory Spray - technically* - Optronic - Gated behind 1-2 cyber only
Tune Laser - Optronic - Gated behind 1-2 cyber only
Repulsor Hypercharge - Optronic - Gated behind 1-2 cyber only
Broadcast Repulsion - Optronic - Gated behind 1-2 cyber only
CS Lacer - Optronic - Gated behind 1-2 cyber only

I propose that we might consider a little rearrangement or allowable target adjustment to more fully separate "help your robot friends" and "everything else" as the former is a niche function.

Additionally, while I was combing through the trees, I found a few more miscellaneous concerns:

Colocation Processing/Dedicated Process - Cyberphysical - Have significantly different names in processes.txt and the tree diagram
Minesweep Pulse - Optronic - Is a node in the tree but has no description in Engineer Processes.txt
Gun Emplacement - Statics - has a description but no tree node
Snare - Statics - Has a description but no tree node
"??????" - Statics - :(

- [ ] Addressed cybernetic ally target structural concerns
- [x] Resolved name ambiguity in "Process" sklills
- [x] Added description for Minesweep Pulse or removed it altogether
- [x] Added tree node for Gun Emplacement or removed it altogether
- [x] Added tree node for Snare or removed it altogether
- [x] Unswaveringly maintained impenetrable crypticism regarding "??????"

**Comment by bleehu** [comment]
This will be done in the next 2 sprints. What do you mean by cyber-only?

**Comment by Turtlelord26** [comment]
A skill that requires a cybernetic player character ally to target.

**Comment by bleehu** [comment]
Some of these issues should be addressed in https://github.com/bleehu/Compound_X/pull/146 I've been awaiting a review for quite some time on this.

**Comment by bleehu** [comment]
I don't really see engineer's reliance on mechanical allies as that big of a problem; Medic relies on organic allies just as much.

**Comment by Turtlelord26** [comment]
Point A: it looks like Medics buff procedures can be self-applied, while engineer ones can't. So unless you built a Detachment A Security Drone Medic, you always have *someone* to use those procedures on.

Point B: I would consider Medic's reliance on organics to be as much of a problem, philosophically if not balance-wise, as Engineer's reliance on robotics. It's about not constraining a player's class choice by other people's race choices. That said, I agree both in flavor and design that Engineer robotic buffs and Medic organic buffs are good to have, and even good to have as a core identity of the classes, but I wonder if we could see them in their own subtrees or coleveled with another, less robot-targeting ability.

Point C: I really don't see the relevance of #146 to this issue. It seems to deal with Medic exclusively.

**Comment by bleehu** [comment]
A: Medic and Engineer should both be able to use their Hippocratic/Repair skills on themselves for no resource gain. Is that not how it's written?

B: I haven't seen either class get hard limited in their ability charging by lack of available teammates. Despite the fact that we have twice as many organic Races as we do mechanical ones, the team tends to split almost down the middle. Since a good dungeon has something for each class to do, there is also almost always some environmental thing for an engineer to repair or improve as well. The extra stuff to repair further prevents engineers from stalling out. 

Point B, rabbit hole 1) The prevalence of Cyborg due to it's being OP has definitely been buoying this effect and when Reveraine rebalances races I expect the number of cyborgs to drop considerably, but not to die out. I also hope that I can push for more mechanical races to maintain this balance.

C: whoops, you're right that's the medic one.

**Comment by bleehu** [comment]
@1sourcecontrol what do you think? EDIT: Specifically about the structural dependency on medic and engineer on biologic/cybernetic races of teammates?

**Comment by Turtlelord26** [comment]
As it turns out, I have been thinking wrongly about most Engineer skills. There are several in the Optronic tree that specify that they cannot be used on self, but most just say 'cybernetic ally' which I guess could apply to a cybernetic self. In an ideal world I'd like to see organic engineers/robotic medics not be too penalized but that's probably a secondary concern.
However, this is the first time I've ever heard anything about not gaining nanites when using procedures on oneself. That is definitely not mentioned anywhere in Engineer.

**Comment by bleehu** [comment]
Ya, I don't see it written either. I'll work on a PR for that.

**Comment by 1sourcecontrol** [comment]
I think, ideally, we'd have abilities arranged so that a medic/engineer won't ever have to pick unusable abilities. For example, if a medic/engineer has all organic with no robotic or all robotic with no organic allies (including, but not limited to, self).

![image](https://user-images.githubusercontent.com/2192156/33160604-94314ffa-cfd2-11e7-9994-8fe693dc4e2d.png)

1. So in this high quality paint image, I think the bottom pair of trees or the top right tree would be ideal. Then a medic or engineer can always pick relevant skills. 
2. Otherwise, I'd think a very even distribution of organic/non-organic abilities might be the answer. Then sometimes they just have to pick an unusable ability. But I really don't like this option for that reason. E.g. "I leveled up, yay! but I can't pick any useful abilities this time... nooooo"
3. Make all abilities applicable to the medic or team or objects you will encounter in some way. So if there always is the possibility of the engineer manufacturing an item that he can use all his mechanical abilities on, this would work. And if the medic had a way to always perform mechanical abilities on fabricated nanites, for example. Or even knowing you will always encounter an electrical panel that you can use your mechanical abilities on. 
But doing this in the reverse seems rather impossible: medic won't likely have an organic target if the whole team is 100% robotic, unless you bring a potted plant I guess (jk)?

I don't like the fact that the two classes can be weakened simply by lack of racial variety on a team. And I think it'd be ideal if that can be mitigated by big split trees where the medic or engineer can focus all of their points on without wasting any.
*Edit* I forgot to mention, I haven't looked in to it, but it'd also be ideal if the cost/effectiveness is even across both organic only and cyber only. I.E., the "max I can put into organic only is 50 tree points (and same for cyber only) and the max tree points i can get at level 20 is 50" (I forget what the medic/engineer tree points are called).

**Comment by 1sourcecontrol** [comment]
Thoughts?

**Comment by Turtlelord26** [comment]
One thing we should be clear on is that Engineers don't have any organic-only abilities and Medics don't have any robotic-only abilities. What we have is a set of restricted-target party support abilities and a set of 'other' abilities in the two classes, with Engineers getting the robotic support and Medics getting the organic support. Engineers can build statics and drones and have a couple support abilities not tied to race, while Medics have an entire tree of direct attacks vs organic enemies. 
<rabbit_hole> Our true disaster case is a robotic Medic in a wholly robotic party fighting a shipful of the robotic pirates. This is prooobably edge-case enough to ignore. </rabbit_hole>

My original aim with this issue was, as you allude to, to decouple the support abilities from the other abilities. I absolutely favor keeping those restrictive-target support abilities in the game, since they're a large part of each class' aesthetic. 

An Engineer without robotic allies will always have fewer options than an Engineer with them, but that just means that that Engineer has to create a build path that neglects the support abilities. Similarly Medic. In an ideal world the Engineer/Medic in an unfavorable racially-composed party will lose versatility and options but not power. This could be considered 'weaker' due to party racial comp, but it's an acceptable 'weaker' if it's only in kind and not scope.

So, I personally would advocate for something like the top-right tree. Having no interconnectivity weakens build diversity in favorable party compositions (organic for Medic, robotic for Engineer). It's a little harder to balance but I think it's worth trying. I just want to avoid the top left tree with other skills gated behind a restricted-target support skill and vice-versa.

**Comment by 1sourcecontrol** [comment]
Good stuff. To be make things more clear, im talking about abilities that only affect certain _races_ (when I say "organic or cyborg only")

2nd paragraph, I agree.
3rd, yeah, that's what I'm hoping might come out of this discussion.
4th,  I don't think I understand the logic behind "no interconnectivity weakens build diversity in favorable party compositions." Can you expound on that?

**Comment by Turtlelord26** [comment]
Sure. Say I'm an Engineer and my party has a couple robots. With little or no interconnectivity (lower tree) I have to choose between taking support abilities and taking other abilities, assuming abilities get more powerful/interesting/versatile as we ascend the tree. With good interconnectivity (more like upper right tree), I can take either kind of ability at each level without forever living at the bottom of the trees. This is exponentially more possible ability sets.

**Comment by bleehu** [comment]
@Turtlelord26, I posit that with the new reliance on non-nanite substances, some of which can be bought that the new Engineer is functional without cybernetic allies, though much better with them. I am eating my own dogfood with my Engineer Opalite character, Mooki. If this turns out not to be the case, we can re-open this issue, but at the moment I would like to petition to close it.
