### ISSUE TITLE
combat 2.0 gunslinger unable to be hit.

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#166]
With the gunslingers new dodge mechanic you can get a +5 to miss with stats. Combine that with both prone and combat roll, you have a +9 for enemies to hit you. and with 2.0's inability to get 100% accuracy "most of the time" it makes the gunslinger very difficult to defeat. the +2 to miss for the next turn is easily negated by prone, and snap shot feats combined.

**Comment by 1sourcecontrol** [comment]
Thanks for the analysis!

I have a couple thoughts on this.
1. You are most likely in the middle of an open space to be prone or behind some structure. If you're behind a structure and nobody is flanking you, and go prone, you can't shoot anyone and can't be shot (so I believe that makes this part of the argument trivial).
2. Going prone gives you a +2 to be hit with melee, and limits your movement.
3. Going prone and using combat roll takes 2 actions. You've consumed half that turn in defense. If you want to combat roll again, you first have to stand up -- causing a 2 action refresh cost, if you will. 
4. Idk if it's listed anywhere, but you can't dodge explosions, so grenades.


So, vs melee, you have some loss of that defense, as well as limited movement.
Explosives still pwn u. 
Gunslingers using pistols will probably have to be at closer range, opening up the higher possibility of getting shotgun wrecked or melee ganked. Combat 2.0 shotguns should not be scoffed at when you have ~40% armor coverage.
You have to minmax very hard to get 50 = reflex+ weapon reflex (to have 5 passive miss chance) at the start of the game, what are you giving up? Also, at level 10+  (you should have 5 passive miss chance by then) enemies will be more dangerous.

What do you guys think? @bleehu  @Wildlovelies  @Turtlelord26

**Comment by bleehu** [comment]
I shall call it "the John Woo Build". 
Explosives are expensive, but not so uncommon with level 5+ enemies that this won't come up. Also, enemies don't pay for explosives with money, so much as their lives. So I think that's a substantive argument. Also for 2 feats, you'll have to be nearing the point where you'll see level 5 enemies anyway. 

You can choose to go prone anywhere. Maybe we need to add language where going prone doesn't actually give an enemy a penalty to hit if that enemy is standing right in front of you? Otherwise belly flopping in front of shotgun guy does actually give you some protection...

**Comment by Turtlelord26** [comment]
I am in favor of prone only providing a bonus against enemies a certain distance away. Off the cuff, how about something like prone provides bonus cover against enemies at least 10m away or half that if going prone submerges you into a light cover (i.e. tall grass)?

As far as the build itself goes, I'd like to see it playtested to see if Source's counterpoints are as ameliorative as they seem.

**Comment by 1sourcecontrol** [comment]
@bleehu 
>You can choose to go prone anywhere. 

True, but it matters where you go prone for the purposes of deciding balance. In my example, it wouldn't matter if you go prone behind a brick wall, because you wouldn't see or be seen no matter what class you are.
My point was this: to actually make use of your pistol-ranged weapons, you'd have to be in a more open space while going prone. 

I also think it's reasonable to put a 10m/5m limit to prone advantages if you are in the open. If you are prone behind cover, even a small table would provide more substantial coverage. In the interest of making the game simpler, I suggest just picking one distance that prone doesn't give bonuses at, unless you are behind cover.

**Comment by Wildlovelies** [comment]
gunslinger's passive specifically states when not in cover, 2 feats means this "could be done" at level 2. and the +2 to miss from combat roll could be negated without snap shot, because of the option the gunslingers get to passively be more accurate with pistols, which i did not calculate with before. so a single feat is all that is needed.

**Comment by Wildlovelies** [comment]
Honestly, I think a more fun, and flavorful option, would be instead of a raw chance to miss, give the gunslinger the chance to shoot bullets out of the air, let him roll reflex spend a bullet, and let them collide within the air. make the dc, what ever the opponent rolls with all bonus' against a reflex roll using your weapon reflex mod. limit it to the range of their pistols of shots they can "sense" coming. it doesn't make sense for a gunslinger to shoot a sniper round from 300m away that he has no idea is coming. but his ability to deter damage is based on his rounds left in the gun, which would make some amusing combinations of pistols, leaving a machine pistol in your off hand for defense and a Deagle in your right for offence, etc. make it so you cant block crits for balance.

**Comment by bleehu** [comment]
Shooting bullets out of the air is a little... Matrix. Maybe _maybe_ after level 10. But I should defer to our directors to comment on aesthetic.

**Comment by 1sourcecontrol** [comment]
I'm nervous about a shooting bullets out of the air. Feels a little too unrealistic. And if we did lean on realism, the gunslinger would be unspeakably powerful if he could move and think that fast.

What if the gunslinger had really fast reaction time, and couple that idea with predicting what the enemy will do? (That's basically how I imagine the gunslinger as it stands) what Steve said gives me another thought: Roll reflex against enemy attacks to dodge them, or something of that flavor. Mechanically the same but more humanly possible.

**Comment by bleehu** [comment]
I believe Pull #225 fixed this issue.
