### ISSUE TITLE
issue with pistol master feat

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#168]
*If you have feat "Quickdraw" in addition to "Pistol Quickdraw",
		negate the action to aim when drawing your pistol(s). When holstering
your pistols after drawing, you must use an action to holster.

Pistol Lanyard  $100
If you drop your pistol, it'll fall harmlessly to 
your leg level instead of dropping onto the ground.
Holstering your weapon is a free action. Drawing your
pistol takes 1 extra Action next time.

So it becomes faster draw your weapon for free, aim for free, shoot, holster your weapon for free, aim for free shoot. etc

**Comment by Turtlelord26** [comment]
I see two potential solutions. We could
1. Draw a distinction between 'holstering' and 'dropping' the weapon in the pistol lanyard rules so that quick draw doesn't apply until after the pistol is properly reholstered
2. Implement an "Immediate Action" system similar to Pathfinder, where Immediate actions are equivalent to free actions except you only get one per round. Then we could make both dropping and quickdrawing immediate actions instead of free ones.

Thoughts?

**Comment by bleehu** [comment]
..."Drawing your pistol takes 1 extra Action next time." If we count that extra, doesn't that balance this out?

**Comment by Wildlovelies** [comment]
this penalizes the character for having both, I say we rewrite it.

negate the action to aim when drawing your pistol(s) **_+*from their holster(s)*+_**. When holstering
your pistols after drawing, you must use an action to holster 

and remove the holstering language from lanyard to say: 

If you drop your pistol, it'll fall harmlessly to
your leg level instead of dropping onto the ground.
Drawing your pistol takes 1 extra Action next time.

**Comment by bleehu** [comment]
We haven't picked a hotfixer for the sprint, have we?

**Comment by 1sourcecontrol** [comment]
What about when the Pistol Quickdraw feat says:

>When holstering your pistols after drawing, you __must__ use an action to holster.

Does this solve the problem?

(Emphasis mine.)
