### ISSUE TITLE
Human race needs buffing

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#169]
Other than aesthetics, humans are completely outclassed by tundari  in every way possible. with the bonus dex and perception and no malices, the effective starting stats of a tundari are 42, equivalent to humans, except the additions give them the ability to min max either of those over 10. As players are always going to put at least one point into both dex and perception, barring an unnatural character build. Plus tundari get additional skills in stealth/ tracking and receive benefits if they are in their preferred terrain and granted low light vision. all with no malices for the class that are directly explicit.

**Comment by 1sourcecontrol** [comment]
Why did you close it? @Wildlovelies

**Comment by 1sourcecontrol** [comment]
Well, I got no response from lovelies.

But I am re-opening this because I think the races need reworking --at the very least, rebalancing.

Humans are rather inferior to other races. Robots have a minor money boost to buying armor, seeing in the dark, boost to max fort/int potential, and are otherwise junk. Cyborgs are incredible -- better than humans in almost every way -- and they will have more skill points than all the other races by level 20 on top of their other bonuses.
Like @Wildlovelies was talking about, take a Tundari if you want dex and perception, because they are *vastly* better than humans if you meet that one requirement.

**Comment by bleehu** [comment]
I'm very concerned about power creep if we simply tune humans to be better. I propose nerfing Cyborg and Tundari. I think Security Droid is already fairly balanced with human.

**Comment by 1sourcecontrol** [comment]
This isn't *power creep*, this is *balancing*. Power creep occurs when **new** content is added that caused previous content to be worthless. 
The introduction of cyborg was definitely an example of power creep. My goal is to bring all the races* into balance -- whether that is through buffing or nerfing.

I think trying to balance down cyborg and Tundari is one good route we can go.

*Fixed a text mistake

**Comment by 1sourcecontrol** [comment]
Also, I think it would be fun and interesting if we gave the races even more benefits/maluses or redesigned their current benefits/maluses (within reason and balance, of course). With the goal of making them even more unique. I don't think we lose anything by making the races stronger, but I do think we add more character and meaningful decision.

**Comment by bleehu** [comment]
Since Reveraine is working on this already, Assigning it to her.

**Comment by Reveraine** [comment]
Done in Dev
