### ISSUE TITLE
High-rolling consistency

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#189]
Currently (including combat 2.0), Armor Coverage rolls are the only roll in the game where rolling lower is better. For the sake of consistency we should consider converting coverage rolls to a roll-high. Mechanically all we'd have to do is take existing coverage values and subtract them from 100, ex. light armor correlates to 70% instead of 30%.

Obviously we'd need a new name for it more in line with "the less you have of it the better", and we can't use Miss Chance for clarity reasons (as in, the chance it ^misses^ your armor). Who has ideas?

**Comment by bleehu** [comment]
In general, I like this idea. It would make me smile if rolling high was *always* good. If we are able to fix this, let's also add language in the design guide to the effect that high rolls would always be good.

In case this wasn't discussed broadly, the thought behind the consistency is that it makes the game easier and more intuitive to learn and pick up to play. 

Maybe we could call the inverse of 'Coverage' something like 'Gaps' or 'Vulnerability'? I'd shy away from 'penetration chance' because it's wordy, and those with a middleschooler's sense of humor might get distracted by the term 'penetration.' Furthermore, I would explain in the Basic Rules or Armor document to the player that we use this odd term to maintain the high roll=good guideline.

**Comment by bleehu** [comment]
In general, I like this idea. It would make me smile if rolling high was *always* good. If we are able to fix this, let's also add language in the design guide to the effect that high rolls would always be good.

In case this wasn't discussed broadly, the thought behind the consistency is that it makes the game easier and more intuitive to learn and pick up to play. 

Maybe we could call the inverse of 'Coverage' something like 'Gaps' or 'Vulnerability'? I'd shy away from 'penetration chance' because it's wordy, and those with a middleschooler's sense of humor might get distracted by the term 'penetration.' Furthermore, I would explain in the Basic Rules or Armor document to the player that we use this odd term to maintain the high roll=good guideline.

**Comment by 1sourcecontrol** [comment]
Like @bleehu said. If we jump at this, my vote is for 'Armor Vulnerability'. Or just 'Vulnerability' -- it's closely associated with the concept.

This conversation reminds when I was first learning this game. I had a hard time remembering that we were supposed to roll over the miss-chance instead of under -- I treated miss-chance like accuracy.

**Comment by Turtlelord26** [comment]
Exposure?

**Comment by bleehu** [comment]
I like both Exposure and Vulnerability. Armor Vulnerability could be easily abbreviated AV. User testing?

**Comment by Turtlelord26** [comment]
A note, "Armor Vulnerability" could be a problem because one interpretation of it is 'the vulnerability *of the armor*', which could lead to confusion (not a lot, but nonzero).
What about Vulnerability/Exposure Rating (abbr VR or ER)?

**Comment by bleehu** [comment]
I think we could mitigate that confusion if we include an armor for free/as the default called "street clothes" or some such, which has a 100% vulnerability. Similarly to how 1sourcecontrol has the default power reactor in his Mechanized game.

**Comment by Turtlelord26** [comment]
Doesn't work. I'd believe street clothes are 100% vulnerable to being damaged.
We all like for it to not be a big deal, but humans and preconceptions :/

**Comment by 1sourcecontrol** [comment]
Hmm... Armor Exposure?

**Comment by Turtlelord26** [comment]
Given that just 5 seconds ago I probably hijacked the word 'rating' for issue 198 I think 'Armor Exposure' or just the one word 'Exposure' would be excellent.

**Comment by 1sourcecontrol** [comment]
Depending on how #243 is resolved, this issue might go away.

**Comment by bleehu** [comment]
Fixed by static armor
