### ISSUE TITLE
Feature Request : Racial Bonuses Rework

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#192]
I propose a new racial system, as no two members of a race are created equal. Kind of along the lines of cyborgs, where you have 'racial' feats or skills and you have X number of points to put into them at character creation (perhaps you pick up more later/per level?)
That way, even among species, there is variety even among them with more than just stat points.
We could also have x number of malices to take, but I don't want to make it super complex, or feel like its punishing to just create a character. 
Thoughts?

**Comment by bleehu** [comment]
I had a dream where all members  of a species were created equal. And were judged not based on the color of their skin, or by their racial feats, but by the merits of their actions!


In all seriousness, I like the idea of having a variety of racial traits that each species can choose from, provided that each of these feats offers differences in kind, are thoughtfully designed and balance well with each other.

**Comment by bleehu** [comment]
What do you think @1sourcecontrol ?

**Comment by Reveraine** [comment]
Oh! Another thought about this that I remembered, is it balances cyborgs. It still gives any race the ability to be a cyborg, but instead of being an addition to racial bonuses, it _replaces_ whichever ones you chose based on point distribution.

**Comment by 1sourcecontrol** [comment]
Like you said @bleehu. I hope we can come up with enough differences in kind/unique pieces so that each race doesn't reuse more than 0, 1, or up to 2 other traits from another race.

@Reveraine can you explain more about, "...but instead of being an addition to racial bonuses, it replaces whichever ones you chose based on point distribution."? Are you saying that Cyborgs will be balanced because every race picks traits that add bonuses instead of just the Cyborg player?
*edit* Oh, I think I just figured out what you are saying. A cyborg character would replace most/all of the non-cyborg race's trait with cyborg ones?

A simple system that I've been thinking about is to have some race-centric trait(s) that all characters have for that race (like maluses to poison, can't have a CHA greater than 10, and/or +1 movement while climbing --whatever you can think up). Then they can pick 2 out of a pool of 8 other traits unique to that race. Something like that.
I'm hesitant to add another big point system that may rival our primary stat system --mostly just a gut feeling regarding how complex the game is. So I figured 'pick 2' would be simple and intuitive enough. But if ya'll have other ideas, I'd love to hear them!

**Comment by Reveraine** [comment]
@1sourcecontrol Yes. Cyborg are not a race by themselves, but instead the cyborg perks are available to all Races, but they are part of the 'pick 2' (or whatever) pool. So they balance out naturally instead of being added to that race's traits. 

I like the double system that you mentioned, where each race has it's own specific traits(like races have now), and then have racial 'feats' that the player can choose. I was also thinking that the chosen traits should not be about stats/combat directly. Unless they are fairly specific? Instead having them influence skills/knowledge/rping and maybe resistances?

**Comment by 1sourcecontrol** [comment]
Ok, thanks! That sounds cool. I wonder if we can come up with other 'sub races' like Cyborg's interactions with other races.

On your second paragraph, Cyborg might not be very interesting without combat benefits from traits --metal arms without health bonuses, for example. Is there a specific reason(s) that you don't want combat stuff directly in the traits? I'm all for cool ideas that aren't necessarily combat. 
Also, having combat stuff in the traits will allow us to get a larger breadth of trait possibilities.

I would kinda like races to be more significant (more powerful) in our design, so it's more noticable that I'm (for example) a human vs a Tundari in mechanics as well as in how we RP. If we pursue that direction, we could potentially put combat and RP bonuses together in the same trait, for most/every trait. Then it's more of a thought on both ends of the combat/RP spectrum, I think?

**Comment by Reveraine** [comment]
The biggest reason was to avoid having to balance them with combat too heavily, but if you're willing to take on that load (or part of it), then I don't have a real problem with it =)

**Comment by 1sourcecontrol** [comment]
I'd be happy to try and balance things! Pending @bleehu's project managing approval. :)

**Comment by bleehu** [comment]
¯\_(ツ)_/¯   Ya'll are above my pay grade on this one. As mechanics director and creative director, once you've agreed on something it's going to happen regardless of my vote. I appreciate you letting me weigh in though. 
In general I like the idea of Racial feats on par with cyborg. My chief concern is how we're going to prioritize it with the other work going on. I think we desperately need a team planning meeting.

**Comment by 1sourcecontrol** [comment]
>agreed on something it's going to happen regardless of my vote

: O  I wouldn't say that! 
I appreciate feedback, especially 3 days after someone shows me that I'm wrong.  If you have an objection, by all means voice it. I'd rather make a better game than get my way --the way I want it.

I was trying to refer to: if you want to have me work on this.. vs working on something else. Since you are the PM, I figured I'd let you decide if you'd rather have me work on powered armor or something.

**Comment by bleehu** [comment]
3 days later?

Thanks for the coffee! 

In terms of prioritizing work, that's part of a larger discussion that we should have over email.

**Comment by 1sourcecontrol** [comment]
>3 days later?

Haha, I was just making a joke to signify "sometimes criticism is hard to take, but 3 days later i'll be fine"

No worries. Sounds good.

**Comment by 1sourcecontrol** [comment]
Leaving this open because work is 'under way'

**Comment by bleehu** [comment]
Please See PR #519

**Comment by Turtlelord26** [comment]
Project Logistics @bleehu 
Since it looks like most of the meat here has been generally accepted, not to mention already integrated into the primary working branch, can we split the Cyborg trait feature request into another issue and close this out?

**Comment by bleehu** [comment]
Absolutely.
