### ISSUE TITLE
Armor Piercing Level and Armor Points

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#198]
"That attack beats your AP level so you take 60 damage to your AP."

It might be nice to rename one of these so the abbreviations are different. Every bit of clarity helps.

**Comment by bleehu** [comment]
The compromise 1sourcontrol and I originally made on this was that AP level is APL; distinct from APs. That said, I garuntee this is going to confuse a new player. Especially one who hasn't played an RPG before who is also trying to wrap their head around how Intelligence is a Stat, but Will is a Save.

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 the specific sentence you quoted, where did you find it?
It should probably say "That attacks beats your APL so you take 60 damage to your APs." then there isn't any ambiguity around which 'AP' is referenced.

*edit* I prefer to use the first character of every word in an abbreviation, when possible. That way, there is more prompting for your memory. Versus calling Armor Piercing Level "AL" or something.

**Comment by bleehu** [comment]
Except when a GM is talking to a player in-game. I don't think Turtle quoted that from the rules, I think he's using a hypothetical situation. I think it's plausible. Maybe even likely. @1sourcecontrol you're welcome to disagree and ask for playtesting if you don't think so.

**Comment by 1sourcecontrol** [comment]
>Except when a GM is talking to a player in-game. 

What are you 'except'ing? Are you responding to my first paragraph or the second? I'll assume the first (feel free to correct me later if i'm wrong).

I mean, if people use the correct terms then there isn't a problem, is there*? My goal here has been to make the rules as easy to adopt as possible -- which means I'm trying to design so the player doesn't won't have to memorize as many things.

*With a rudimentary understanding of the armor rules, there are several ways that the proper terms can be inferred by imperfect usage: APL is a single digit number, 90% of the time. APs are double and triple digit numbers, 100% of the time. A player may reduce your "Armor Piercing Level", but they will never do damage to an "Armor Piercing Level" that is a property of guns and armor. Damage can only be dealt to a type of hit-points: "Armor Points". With even one or two of these pieces among the rule reading, you can say, "hmm, ok, Turtlelord must be referring to Armor Points when he said "AP" because we already compared AP level".
I tried my best to come up with terms that are both intuitive to the mechanics and to the realism. That being said, I'm all for a different term if it makes sense because I'm as imperfect as the next cat.

**Comment by Turtlelord26** [comment]
Confirm was a hypothetical GM statement.

Unfortunately, and I like it about as much as you do, 'if everyone just uses the terms correctly there won't be a problem' isn't sufficient. If there is a not-insignificant chance someone will misuse a term - or even accidentally say the wrong one while thinking of the correct one - it will cause a play slowdown while another player corrects them with information like the stuff in your asterisk note. And most people, especially nontechnical people, are susceptible to misterming or mispeaking simply because they're focusing on the game they're in instead of the rules, as arguably they should be. 

So, if we can find an alternate term that's as good as what we have, we solve one small but existent problem at no cost to the game.

I will mention that the concepts and system you designed are excellent and are staying in the game regardless of what we end up calling them. In no way is anyone here trying to diminish them.

On the technical side, I am of the opinion that Armor Piercing Level should stay due to how ingrained armor piercing is in the public consciousness. That suggests we should look at possible alternate names for Armor Points. "Armor Rating" and "Armor Health" come to mind, though armor health is problematic if we ever decide to implement an equipment sundering mechanic. Armor rating seems good though, as in 'this armor is rated to take this much punishment in this unit of time'.

**Comment by Turtlelord26** [comment]
I was glancing through the armor list when I saw that our term for the exact equivalent stat to Armor Points is "Shield Strength". In the interests of standardization I would propose we call both of these either Strength or Rating.

**Comment by 1sourcecontrol** [comment]
Alrighty, thanks Turtle.

Shield Strength vs Shield Rating
Armor Strength vs Armor Rating
Idk about Armor Rating. Would that get confused with Armor Piercing Level? 'Rating' and 'Level' carry similar meanings. I guess my vote is more towards "Strength" for that reason.

**Comment by bleehu** [comment]
I think I lean toward calling both 'strength'

**Comment by Turtlelord26** [comment]
I stand outvoted. Let it be so.

**Comment by bleehu** [comment]
@1sourcecontrol would you mind doing the work for this?

**Comment by bleehu** [comment]
Fixed
