### ISSUE TITLE
Favored Classes

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#207]
I kinda hate the idea that certain races favor certain classes. I really like that a security drone or human can be whichever class they want and do it well, even if their approach to say, Hunter, might be a little different. 
Should we keep Favored Classes?
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/01_Races.txt#L92
DnD does it, but I'm not sure they're better for it.

**Comment by Reveraine** [comment]
I think that, while it makes sense that different cultures favor certain 'career' paths, I agree that it seems exclusive. I think that we should make that a part of background, not race. And that way it can be far more flexible. 
While we'll have a set number of base backgrounds, that is one thing that DMs and Players can have a lot of control over. Eg. while an aristocrat might have gone to school to learn to be a doctor, perhaps a different individual from the rim picked up their combat medic skills in a different way. Making backgrounds have specific classes they favor doesn't seem off to me, mostly because it allows this freedom. It also makes more sense than race-specific classes. Of course, depending on where we go with things, there may be some aliens that can just do things that others can't, but we haven't hit that point yet.

**Comment by Reveraine** [comment]
Also,
While we do have racial stat bonuses that may appear to favor a certain class over another (which I think is fine). It should not be stated as such, and that should be something that players can decide(or not). For instance, Stephen is an optimizer, and will find the favors whether they are stated or not, but others will find challenge in not playing the most optimized character, and thus will not always play a Tundari that takes advantage of their speed. Unfortunately, we can't completely stop the attitude of favoritism as far as races/classes without making race a purely aesthetic choice, which dilutes the realism by a large jump, but we can keep it out of our core rules as far as avoiding planting ideas in our players' heads.

**Comment by bleehu** [comment]
I strongly agree!
>  It should not be stated as such, and that should be something that players can decide(or not).

**Comment by 1sourcecontrol** [comment]
> I kinda hate the idea that certain races favor certain classes. I really like that a security drone or human can be whichever class they want and do it well, even if their approach to say, Hunter, might be a little different.

I simply took "favored classes" to mean "Hey new player, if you want to take this class, then it will easily work well with the following xYZ classes!"

I am rather ambivalent towards keeping or removing the "favored classes" text. If you guys think it's better to remove it because "aesthetics" then I'm all for it. As far as I know, there aren't any rules limiting races to any given class. (Which appears to be your sentiments as well, I'm just trying to be really clear because @bleehu 's initial statements implied to me that races have a requirement to take certain classes). I certainly agree with the thought that shackling classes to certain races is a bit poopy. Unless a class arises that only makes sense for a mechanical race or something.

**Comment by Reveraine** [comment]
> I simply took "favored classes" to mean "Hey new player, if you want to take this class, then it will easily work well with the following xYZ classes!"

I feel like this would go very well in a 'new players' section. Something like "For those new to Compound X, we suggest starting with a Human or Security Droid Soldier (or whatever we decide on).

**Comment by 1sourcecontrol** [comment]
Sounds good!

**Comment by bleehu** [comment]
@1sourcecontrol , do you got it? Or should I assign it to Turtle or myself?

**Comment by 1sourcecontrol** [comment]
turtle or you sounds good
