### ISSUE TITLE
Formalize Aiming

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#217]
We talk about aiming a lot but I think we're all working under a collective assumption of how that works. It might be advisable to formalize the combat state of "being aimed".

Probably something like:

Aim action becomes: Spend one action to gain the Aimed combat state against a target you can see within your weapon's longest range bracket.

New Combat State: Aimed (X), where X is the entity at which you are aiming.
While aimed at a target a character may fire at them without blind-fire penalties. Aim persists until dropped and may be dropped as a free action. Aim is automatically dropped if the character hunkers behind cover or otherwise loses direct line-of-sight to the target.

Technical Directors' Thoughts?

**Comment by bleehu** [comment]
If you have a question specifically for 1Source, go ahead and '@' him. @1sourcecontrol

**Comment by 1sourcecontrol** [comment]
Yeah, I see your point. I never thought to formally define 'aim' because we use it with its typical meaning. And while I'd rather not add the complexity of defining it, defining (hopefully) removes ambiguity. 

I suggest being careful not to gamify the term too much or we'll make it unintuitive.  In this instance, all I'd intend to do is describe how the game behaves like real life, only time is broken up into actions. Wherein it takes a single action to carefully point your gun at something.

1. If you can rephrase it so that "Aim"/"Aiming" is described like above (a guideline with some formality) that'd be ideal. Quite a bit of DM choice has gone into aiming, where, if you are aimed "close enough" to a second target then you get to negate the action taken to aim. That isn't formally defined, but it's naturally understood because we know what 'I am aiming at x' means in real life. If we formally define all that's possible and what we want to be possible, it might take a lot of text.

2. If option 1 seems unacceptable, then I have some edit thoughts:
>Aim action becomes: Spend one action to gain the Aimed combat state against a target you can see within your weapon's longest range bracket.

I think we should say "weapon's maximum range" instead of "weapon's longest range bracket." It isn't  clear to me whether you are talking about 'within the maximum range' or _specifically_ 'within the weapons longest range bracket __exclusive of closer-ranged brackets__.' Although, it's totally legitimate to aim at a target outside of your maximum range and wait for the target to get within range... i.e. in an ambush.

>Aim persists until dropped and may be dropped as a free action. Aim is automatically dropped if the character hunkers behind cover or otherwise loses direct line-of-sight to the target.

I would remove "or otherwise loses direct line-of-sight to the target" or rephrase it somehow. You'll still be aiming at where the target was when you lost sight, whether or not the target is there. So you'd continue to be aimed if the target went behind a wall and came out again. 

@bleehu what are your thoughts? I'm not totally sure on this one.

edits __in bold__

**Comment by bleehu** [comment]
What's interesting to me is that this is so fundamental, but doesn't seem to have come up as a problem. I wonder if that's because we keep explaining it verbally as common tribal knowledge, or if it is indeed intuitive? 
I do strongly agree that one should be able to aim at things they can't necessarily hit. I also really like how Turtle formally defines how CQB weapons work at close range. This has my approval for doing work. I would classify it as awaiting assignment.

**Comment by 1sourcecontrol** [comment]
@bleehu , I've missed something.

>I also really like how Turtle formally defines how CQB weapons work at close range. 

Where is CQB defined?

**Comment by bleehu** [comment]
Ah. I was confusing your recent pull with the potential for adding CQB language to new aiming rules.

**Comment by bleehu** [comment]
So do we greenlight this? Or send it to testing?

**Comment by 1sourcecontrol** [comment]
@bleehu  I'd say, greenlight.

Related question: I don't understand. How do we 'send it to testing' before the rules exist?

**Comment by bleehu** [comment]
What we would test is the existing interpretation of someone who hasn't played yet before to see if it is intuitive, but let's greenlight it.

**Comment by bleehu** [comment]
@Turtlelord26 if this is fixed to your satisfaction, please close it out. If there's more to do, please let us know what that is.
