### ISSUE TITLE
Paladins not included in new wep/ armor feats

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#26]

**Comment by trowl223** [comment]
The new feats were not added to power up all classes, they were added because some classes it made sense to have certain armours or weapons available if the player wanted to make a certain character. It was a compromise between having very strict classes that may alienate players with creative ideas, and having a generic "Learn X" feat that would allow any class access to any weapon or armour which may break certain classes (think of an assassin with a shotgun). Paladins did not fit into any of the armours or weapons after Bleehu and I discussed each feat/weapon/armour/class. If you disagree, please let me know in a private message and we'll discuss it.
