### ISSUE TITLE
Weakness To Poison Mechanics

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#290]
https://github.com/bleehu/Compound_X/blob/08c546897515dab2a3543e1eafc554be727aba25/CharacterCreation/01_03_Races_Tundari#L44

Weakness to Poison/Contagions needs to be added here by a balancer.

**Comment by Turtlelord26** [comment]
I could see doing any of 
1. Roll poison and contagion related saves with disadvantage
2. Take a flat penalty to such saves
3. Take a penalty to initial infection saves but not to subsequent recovery saves.

My personal favorite of these at the moment is combining 1 and 3. I particularly like 3 because it communicates the feeling and experience of increased poisonability but doesn't necessarily apply the unfun ugh-I'm-poisoned-forever feels. May also result in easier balance of poisons.

What ideas does everyone else have?

**Comment by bleehu** [comment]
I concur with Turtle's analysis. I think you're developing a good instinct on what is fun and what isn't. =)
