### ISSUE TITLE
Regular Feat # Tracking Ambiguity

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#30]
In the classes document it explicitly states that a level zero character has no regular feats. However in the Basic Rules document it states a character gets a feat every second level but in the table shows characters having 2 feats at level 2. It doesn't say anything special about level two, so the table would appear to imply a feat exists at level zero (also consistent with the 9 Cha feats column). Which is it?

Also, while I'm here, what does "Static" mean in the level 1 skill point column?

**Comment by trowl223** [comment]
The Classes document is correct. The Basic Rules document is correct too, as is the table. Eliminate the impossible, and whatever is left, however improbable must be true.

The rules table shows that a level 2 character has 2 feats. The classes document says that a level 0 character has 0 feats. This does not imply that a level 0 character has 1 feat, that would not make sense. All that remains is that at level 2 you gain 2 feats, which is how I intend the process to work.

Level 1 skill points are marked as "static" because during character creation you get to choose 5 skills, all with a bonus of 10. This needs to be written in the rules as I don't think its anywhere anymore.

**Comment by Turtlelord26** [comment]
Two feats at level two it is, though I would recommend spelling this exception out somewhere near where it says you get +1 feat every even level, as that is explicitly inconsistent otherwise.

If static refers to character generation skills, does that mean that a character does not receive skill ranks for leveling from zero to one? If so (which makes sense as taking a class is a decent amount of learning by itself), it may be clearer to explicitly include level zero in the table and write the level one skill point gain as +0.

**Comment by bleehu** [comment]
I'll Clarify this and close it out.

**Comment by trowl223** [comment]
Approved merge, closing issue.
