### ISSUE TITLE
Gripes - Burst Fire

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#338]
Burst Fire weapons need their specific fire rate written down.

**Comment by 1sourcecontrol** [comment]
Is #321 sufficient?

**Comment by bleehu** [comment]
Technically, yes. You can close this.
But I had to read it a couple of times before I understood the semantics of it. It would be a lot more intuitive/clear if burst rate was listed next to auto rate.

**Comment by 1sourcecontrol** [comment]
If it needs to be reworded, let's reword it.

>It would be a lot more intuitive/clear if burst rate was listed next to auto rate.

If burst rate was listed next to auto rate, in the weapons document? We could add a line at the top of the relevant weapon docs, similar to suppression. E.g., "Burst fire rate is 3 shots per action unless otherwise noted" Auto fire rates could also be listed. Up to this point, all burst fire rates are 3 shots, I believe. And the majority of auto fire rates are 6.

**Comment by 1sourcecontrol** [comment]
Actually, I took a look at the weapons documents and the weapons **_already have_** burst fire rates listed. Do we know who this gripe originated from? Because it looks like they didn't read the document correctly, or something else is going on. If readability with a semi-colon is the problem, we can separate out some of the lines. But If they didn't read their weapon specs, there's nothing I can do.

This exists for carbines and some SMGs (although the spacing got increased from the stylization):

![image](https://user-images.githubusercontent.com/2192156/36410178-527070a4-15c4-11e8-9064-17be7966d294.png)

Assault rifles typically have more than 2 fire modes.

Preferably, we can attend the point I made in the above ^post^ because that would reduce the file length and simplify things if the readers understood that most weapons have burst fire rates of 3 or auto fire rates of 6. It would also help the reader digest information if the weapons listed less unique stats. 

Here are some screenshots of carbines, assault rifles, and smgs:

![image](https://user-images.githubusercontent.com/2192156/36410090-e02cdd34-15c3-11e8-881b-408ed75c1c1f.png)

![image](https://user-images.githubusercontent.com/2192156/36410101-e8903e44-15c3-11e8-84c4-b4c98aada6de.png)

![image](https://user-images.githubusercontent.com/2192156/36410124-01e3d9aa-15c4-11e8-9e7e-e1a35b65a07d.png)

**Comment by Turtlelord26** [comment]
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/04_04_Carbines_AssaultRifles_%26_BattleRifles.txt#L39

https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/04_04_Carbines_AssaultRifles_%26_BattleRifles.txt#L52

Counterexample, 2 burstfire carbines without a burst fire rate stat.

**Comment by 1sourcecontrol** [comment]
Ahhh, ok. That makes more sense. Thank you.
