### ISSUE TITLE
Move to change "Race" to "Species"

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#341]
After some discussion, even though we are accustomed, through other RPG's, to calling the different species 'races', some discussion was brought up wondering if it would make more sense to call them species and sub-species, and leave 'race' as we think of it up for interpretation from the players.

**Comment by Turtlelord26** [comment]
Yes.

**Comment by Turtlelord26** [comment]
I've seen other space RPG systems that use the species designation and it didn't seem out of place at all in any of them.

**Comment by bleehu** [comment]
I agree. Species makes more sense to me.

**Comment by 1sourcecontrol** [comment]
Are we being different for the sake of being right? Or being different for the sake of being different? Or being r........ 
I have a hard time landing in either camp -I can find almost the exact same definition for both- when flipping back and forth between the words on merriam-webster.   ¯\_(ツ)_/¯

**Comment by Turtlelord26** [comment]
Warning: possibly unnecessarily long and slightly technical explanation ahead. This is why I tried to get away with a one word response earlier.

In the world of biology and anthropology, species has a technical definition of approximately "a group of organisms that produce viable, fertile offspring within the group". It gets muddy sometimes, ex the famous case of an east coast frog species, but mostly it works.
In that same world, race does not have a technical definition. Races and ethnic groups are not useful constructs (excepting use as cultural units).

Referencing the merriam webster pages you mentioned:
While they may look similar, they aren't. The most important parts are (1)Species 1d(1)

    "a category of biological classification ranking immediately below the genus or subgenus, 
    comprising related organisms or populations potentially capable of interbreeding..."
which is the closest it gets to the technical definition, and (3)Race 3c

     "a category of humankind that shares certain distinctive physical traits"
which is what 99% of people think of when they hear the term. Again, it's not a useful construct for talking about biology, since genetic variation within each "race" greatly exceeds variation between them. That (3)Race 3a (which is similar to (1)Species 1d(1)) exists is irrelevant when pretty much everyone is going to hear (3)Race 3c. Species does not have that baggage and is more technically accurate anyway.

One other note, fantasy settings can get away with it because A. they're fantasy and B. many of their races can in fact interbreed with others to some extent. My impression was that we were going for a more realistic level of interbreedability (i.e. none because even if the Tundari equivalent of protein encoding data storage somehow miraculously looks vaguely like a chromosome, they almost certainly have a different number of them).


So, we would be "being different for the sake of being right", except as previously mentioned loads of systems with playable aliens use species already, so it's not really all that different.


(I took an intro to anthropology elective, and the professor spent a week on this.)

**Comment by 1sourcecontrol** [comment]
Alrighty. Thanks for the anthropology lesson!
I've had it ingrained in me from fantasy games (I guess) that race means "a group of biolgically distinct creatures." Which would explain a bit.

**Comment by bleehu** [comment]
Can we call this approved, then?

**Comment by Reveraine** [comment]
Completed
