### ISSUE TITLE
Proposal for the Streamlining of Melee Combat

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#356]
This is a discussion issue and can be separated into action items as components are agreed upon. However as they are all related to each other it seems fair to discuss all at once.
Source: Thought experiments related to building a dungeon that emphasizes melee combat.
https://github.com/bleehu/Compound_X/blob/dev/01_01_Basic_Rules.txt#L755

First, regarding the Guard DC, (which I don't think would suffer from being renamed to just "Guard"), I would like to simplify the calculation and shift the dependency from the raw stat (which we use everywhere) to the stat modifier (which I don't think we use nearly often enough). One thing that allows us to do it make the Guard a simple division of the total skill rank + ability mod = total skill. Probably (?) a divide by 10 to start until testing.
Basically I see no reason for a number that will rarely come up, but be very important when it does, to have an even slightly arcane calculation.

Second, I'm not sure about the necessity of an entire phantom second health bar for nonlethal damage. It seems simpler and not significantly less accurate to rule unconscious vs bleeding out solely on whether the last hit was lethal or nonlethal.

Third, re grappling: This paragraph needs a clarity pass. The way it reads, I'm not sure whether a declared grappling attempt is an automatic success. I also don't like the attack of opportunity grappling provokes from the target - that seems unrealistic. Finally, it seems unnecessary that grappling should be a skill separate from the general melee combat skill. The irl skills can be slightly different, but they are very closely related, and as CX is primarily a cover-based shooter, I think we can afford to lose that particular level of granularity.

Fourth, I'd like to see shove be a contested skill like grappling instead of just an attack roll. And should have the option to force the target prone (trip) and shove in more directions than just away. Those might be harder than the base shove.

Fifth, despite it raising complexity a bit, I think we should have some explicit rules for the ranged character with a non-CQB rifle who is forced into melee combat. Even if the rifle isn't fireable, it's still a useful weapon.

The general philosophy I think we should have towards melee is that it is a corner case of CX (despite the assassin class's predilection towards it), so it should be kept relatively simple and very self-consistent so that the majority of players who will barely touch the stuff are able to scan it quickly when it does come up.

Speak, o ye fellow devs, and be heard! Everything in that wall of text is fair game. 🐢

**Comment by rosebrallier** [comment]
Melee a corner case? That sounds like a CHALLENGE.
On a more serious note, I think we should either include Guard as a basic part of PC and NPC stats or straight up remove one step in the calculation. Multiplying a stat on the fly by .4 is mean to your GMs.

Second: I would treat the issues of rendering an opponent unconscious vs bleeding out by having the attacker call nonlethal intent when they hit. Then, the damage from that attack would cause unconsciousness if it would otherwise cause bleeding out. If the target still has hp, then YAY, the attack was definitely nonlethal, but you can't change whether future attacks are lethal or not. It makes for more interesting rp if your ally destroys a target you were trying to keep alive, and makes players communicate with each other instead of using combat mechanics alone to achieve their goals.
[Slight tangent: wtf are "Full non-lethal" and "half lethal" damage. that description is intensely unclear.]

Third: Perhaps bonuses to (specifically) grappling could come in the form of feats or abilities. Seems to me that unarmed combat should definitely apply to grapple checks with a character's grappling ability/training added on top.

Fourth: Aye aye.

Fifth: I believe using your gun as a bludgeoning weapon should fall under improvised weaponry, maybe with damage based on the usual Str, Dex, and the weapon's damage-yness (aka weight as indicated by the Str requirement or by weapon type.). Speaking of, we should develop a framework to apply to improvised weapons like hitting someone in the face with a frying pan. Or a wrench! Or a giant wooden mallet! Or a baseball bat with nails sticking out of it! This will prevent (terrible) people like me from giving every single one of my PCs unconventional melee weapons until the GM codifies a way to deal with them.
I recommend a melee weapon attack with the usual Str- and Dex-based (primarily Str) damage plus (essentially) weapon weight plus bleed for poky bits!

![image](https://user-images.githubusercontent.com/32423723/36930937-e0191cae-1e60-11e8-8705-428b9bcd70c3.png)

**Comment by bleehu** [comment]
My thoughts:
> Basically I see no reason for a number that will rarely come up, but be very important when it does, to have an even slightly arcane calculation

Totally with you here. 

> Second, I'm not sure about the necessity of an entire phantom second health bar...

This was a relic from design that Trowl did back in the day. I'm very ok with replacing it. There is some hand-waving involved because bullets and knife cuts don't really knock you out, but I'm willing to make the trade of fun-for-gamey. 

> Grappling

I'm punting on this, because I haven't met a tabletop grappling system that I like yet. Grappling is near and dear to my heart because of my wrestling background and it's potential for fun enemy design if it's done right. But until I have solutions, not just complaints, I'll hold my tongue. 

> Simplicity

Don't forget that Assassin and Berserker both lean heavily on melee combat. And Rose has made a melee-focused Hunter, because explorer. It is clear to me from testing that melee combat in a shooter strongly figures into the fantasy that many players enjoy. (see, sword and grav hammer in Halo, etc). I agree that simplicity is to be prized, but I think we should keep in mind that melee combat is an essential case, even if it's a less-focused one.

**Comment by bleehu** [comment]
Also, I should mention that one of the things they teach you in gun safety classes is not to bludgeon anything with the butt of your rifle; that has the tendency of making the weapon go off wildly. If you're in melee combat and you happen to be holding a sniper rifle, you're much better off dropping it and going for your knife than trying to use it as an impromptu baseball bat.

**Comment by rosebrallier** [comment]
Re: Using guns to bludgeon
Just because something is ill-advised doesn't mean we shouldn't have rules for it. In fact, we should definitely have rules for how spectacularly badly it could go!

**Comment by Turtlelord26** [comment]
One unfortunate thing about involving a skill in a combat like this is that when we translate from d100 skills to d10 combat, we lose so much precision. No matter how it goes, if a Melee Combat skill is involved in to-hit calculations, only one point of every ten matters, and the other nine do nothing.
Does anyone have a clever idea to make this feel less bad?

**Comment by Reveraine** [comment]
I think if we start framing skill points like experience points, that might help it feel nicer. So every time you hit that ten, you've 'leveled up' in that skill. I don't think we should use those words, but I think we can make it feel nice with the wording.

**Comment by Turtlelord26** [comment]
I'm specifically concerned with the encouragement those dead points provide to metagaming your stats. If you're at one of the melee skill breakpoints and level up, it is most mechanically correct to put 10 points into it or zero. 10 points is almost always more than half of what a character is getting per level. If a character relies on melee, the system is encouraging a very min-maxy skill allocation. Also, corner case, but the character with <5 cha and int cannot hit a breakpoint in one level and so is forced to allocate dead points in order to advance later.
Further, if skill caps by level ships, it gets even worse because now there are correct levels to dump all your skill into melee and correct levels to focus on everything else, instead of allowing steady growth.

...I wonder if we could strip the skill out of attack and guard calculations and provide indirect bonuses like the various gun type skills. That would be like the 'level-up' feel but with less distance between levels.

**Comment by bleehu** [comment]
I agree to the idea of taking the skill out of the combat calculations. I don't know that it makes a lot of sense to incoming players, but the way skills are now, it scales very poorly.

**Comment by Masterdiekillsu** [comment]
I feel with melee, we have to approach it in a similar manor with gun
accuracy but with a system that works fluidly along side shooting, but
works without confusing the two, and being realistic enough. Melee should
NOT have any skill buffs that add to it. That being said, I can probably
work out a couple ideas that might make weapon fighting easier to work
around. It'd take me awile to write all up, but I could do it. I'd also run
it by y'all first so anything needs balancing or fixing.
First idea is to work out what the hell a "guard DC" even is, and get it
explicitly stated. Then get people to calculate it. Then we go to what
melee combat actually is and how that works.
Second is to then make it universal, so that a min/max melee character
isn't unbeatable by someone who isn't melee. This also opens up the
possibility of fist fights being something completely doable now. Melee
won't be ground into the ground dangit!!! It will be balanced!!

**Comment by Turtlelord26** [comment]
I detect a volunteer! (thank you).

It looks like we're converging on a consensus re the five points (**if I'm wrong please screech at me, inbred design is bad**), so I'll make some action item issues entitled Melee 2.1. Go ahead and take as many of those as you want. Some of them will have specific requests based on the above thread, but if you have a reason to do something differently please feel free to make the case.

**Comment by Turtlelord26** [comment]
2 weeks of non-screeching and the diaspora of points to individual issues would seem to indicate that this issue has fulfilled its purpose 🐢

**Comment by 1sourcecontrol** [comment]
(Btw I'm taking these text snips from the dev copy)
There is some slight rules for added effects from using a gun as a club:
https://github.com/bleehu/Compound_X/blob/c93e71a5d51edc797a592d66ac76089085b5a2da/01_01_Basic_Rules.txt#L1215

Three thoughts on melee weapon skill.

1. Melee attacks are seriously disadvantaged by the large gun ranges and the huge lethality of guns at close range. Melee weapon skill allows a melee-focused player to attain very high accuracy in melee so that they won't be widely disadvantaged (extreme chances to die if you miss melee attacks with enemies close by) compared to using shotguns or other ranged weapons that can be used _potentially-more_-safely from cover. That was my past thought, anyhow.

2. I added damage scaling for melee and thrown weapons based on melee weapon skill (see text section given by the snippet below). That was to increase the melee and thrown weapon damage to moar useful levels -with stealth kills in mind- and giving the unarmed expert better damage. Also rewards melee/thrown weapon players with the ability to potentially do more damage than an unskilled opponent. (Idk if ya'll removed melee weapon skill from the game or not --that's why I bring this up.)

3. Are you removing melee weapon skill from accuracy calculations based 'on principle' as a reason? (Meaning, removing melee weapon skill because it's a skill affecting melee accuracy) What about thrown weapon skill and thrown weapons/grenades? _Just a thought_ 

https://github.com/bleehu/Compound_X/blob/c93e71a5d51edc797a592d66ac76089085b5a2da/CharacterCreation/04_01_Melee_%26_Thrown_Weapons.txt#L10

Hope that sheds some light on my thoughts.  :) Have fun!

**Comment by bleehu** [comment]
Thanks for your thoughts! It's super helpful to have some insight into the massive amount of design work you've done beyond just the product of that design.

**Comment by 1sourcecontrol** [comment]
Thanks! :)

**Comment by Turtlelord26** [comment]
The current design direction removes skill from directly modifying accuracies, but it will still benefit your melee prowess by a similar mechanism to your 'proficiency skill feats' for gun types. I did not like the granularity enforced by translating directly from a d100 to a d10 scale.

And yes, thrown skill directly affecting accuracy is also in for it. Thanks for reminding me about those.
