### ISSUE TITLE
Redesign Request: Missing Armor Deals Half Damage

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#384]
This idea was very nice aesthetically and served a good purpose mechanically, but only really works in the midrange of armor stats. Check out these corner cases:

The Full-Armored squish: 100% coverage but zero AS, dies like a DnD Wizard because every shot is max damage.
The Armorless tank: Have tons of Fort and buy one medium armor arm rig with an armor mat. 90% of shots do half damage, and the other 10% has to get through your AS. Total cost: dirt cheap.

I am of the opinion that it will make far more sense to set a permanent dividing line between shots that deal full or half damage. 

Example section: For the sake of argument, lets say 60% of the average human is vulnerable to full damage per shot. Further suppose that a target has 75% coverage. Then:

Armor rolls of 1-60 would deal full damage, first to AS and then to health.
Armor rolls of 61-75 would deal full damage to AS and half damage to health. If a shot removes the last AS, half the remaining damage is removed from health.
Armor rolls of 76-100 would deal half damage to health.

If the target instead had 50% coverage, the difference would be that rolls in the 51-60 range deal full damage to health, ignoring AS. The outer ranges would function the same. Essentially, lighter armors may not cover all vulnerabilities, and heavier armors might be extensive enough to cover less vital areas.

Some implications:
1. #189 is a lot muddier since sometimes it will be better to roll low and other times it will be better to roll high on armor coverage (and other times, like in the above example, the best rolls are in the middle). This is actually already the case, but this proposal would make the muddiness more consistent across characters.
2. The dividing line between full and half damage shots provides another possible handle for balancing races. Maybe Plizards have fewer vulnerable organs than Opaleites. Maybe robots can spend a race trait to move that bar downward.
3. Technically increases dice rolling as now 100% coverage characters may still have to roll.

I would like to collect reactions from some number of devs before yellowlighting my own idea.

**Comment by bleehu** [comment]
Good catch on those edge cases. I hadn't though of those. 
Of your three drawbacks, I don't see anything particularly concerning. But I think it should be noted that having to memorize/write on the character sheet _another_ magic number is a small amount of complexity creep. But in this case I think it strictly improves the system. 

The alternative is to minimize complexity by scrapping armor rolls altogether. This was a good idea of 1Source's that he left before he had time to implement. It basically trims the least fun roll from the game, reducing complexity and speeding up turn rounds. The value of armor would be folded into the accuracy roll. So the more accurate a shot, the more likely it would be to miss armor and hit something vital. 

I'd be happy with either change, as Turtle (and 1Source) have convinced me thoroughly that the existing system needs improvement.

**Comment by Turtlelord26** [comment]
I would be really happy if we came up with a clean, smooth, and playable implementation of folding armor into accuracy rolls and scrapping armor rolls entirely. But I think that might take some time, and who knows where it'll end up in the new priority ordering. How about we slot that as a project, and implement my original suggestion in the interim? (Dropping the possible racial complexities for now, just decide on one number for everyone and see if it helps the play experience).

**Comment by bleehu** [comment]
Sounds like a very sensible solution!

**Comment by 1sourcecontrol** [comment]
The last armor idea I went with was to nix armor percentage and give all armor a 'passthrough' number, where a certain qty of damage would always go through armor, depending on the armor. Which leaves simple addition and subtraction instead of die rolling and division.

I still have the prototype written up in excel, if you guys want it sometime, maybe we can go on discord and discuss it.
(The only reason i didn't release the prototype before I left was that I didn't have the cost equations finished and/or some of the other values. But it's almost playable.)

**Comment by 1sourcecontrol** [comment]
> ###  The Full-Armored squish: 100% coverage but zero AS, dies like a DnD Wizard because every shot is max damage.

As far as characters go, this situation shouldn't be possible by the rules for 2 reasons:

1. The armor is basically clothing without an Armor Material so the Coverage wouldn't matter. It's  implied to me by 0 AS and no stated APL that the player doesn't have any armor material installed.  (I imagine that the first sentence, below, should've been written more verbosely)

>Also, Armor systems do not include any protection
without an Armor Material. If you purchase more than one Material* to cover 
your whole body (installing in the Arm, Leg, and Chest Rigs, for example) it 
improves the Armor Coverage (% of Armor protection), but not the quantity of 
the Armor Strength (AS) or the Armor Piercing Level (APL).
https://github.com/bleehu/Compound_X/blob/b661ea706f269efa32858338d4d8ee525399afad/CharacterCreation/05_ArmourList.txt#L21

2. Every shot under 50% is max damage, over 50% is half damage. This was added so that a player wearing 100% armor wouldn't be at a disadvantage compared to a player with less armor coverage.

>If the attack misses armor, or 
rolls over 50%, it does half damage because the bullet is hitting a less vital 
part of the body.
https://github.com/bleehu/Compound_X/blob/b661ea706f269efa32858338d4d8ee525399afad/01_01_Basic_Rules.txt#L895

> ### The Armorless tank: Have tons of Fort and buy one medium armor arm rig with an armor mat. 90% of shots do half damage, and the other 10% has to get through your AS. Total cost: dirt cheap.

1. Interesting scenario. When I made the excel and made the armor rules into text, I thought I had written down a restriction to the effect, "the player has to equip chest armor material before equipping other armor materials". I guess that never made it down into the armor rules. I imagine that might be balked at as too controlling, maybe that's why it didn't make it? Lol, one less tiny rule, probably for the best.

2. How tanky is it, really? A player min-maxing lets say 12 stat points to Fortitude gives 170 Health (unless the formula changed?) 3 shotgun blasts would almost certainly kill, 5 assault rifles bullets would kill, and a grenade could do half health* and add bleed. The average player (6 stat in FORT) would be laid waste by 2 shotgun hits or 3 assault rifle hits.

3. Conclusion, I think I passed up this scenario as concerning (in the armor 2.0 design) because one good set of shots from a challenging opponent would kill you if you weren't careful. (Min-maxing players will certainly be above the health curve, but is it too much above?) My plan was that the average player would much-more-easily die without having any damage absorption through AS. But it does seem abusive to the system, to me, to have half damage for almost all hits. 

*This reminds me, when I wrote the grenades, I intended them not to take the half-damage penalty for missing armor, was that written clearly in the grenade descriptions? If not, it's your prerogative to decide.

**Comment by Turtlelord26** [comment]
Confession: we've been playing your armor system wrongly. I somehow never noticed that bit about rigs requiring a material to provide coverage. We shall try it properly and revisit armor issues afterward.

Closing this issue as the far more important half of it is apparently already in the basic rules as linked above. X| X| X|
