### ISSUE TITLE
Grenade Damage Type Pass and Sanity Check

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#493]
https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt#L290

1. Frag grenades don't specify damage type for primary hits. I believe we want it to be ballistic damage.
2. CID grenade doesn't specify damage type. (Internal?)
3. Plasma grenade doesn't specify damage type. Definitely plasma.
4. C10 and RMM HiEx do specify explosive damage, but see #491

5. These new frag grenades are concerningly complicated. I don't remember seeing them get changed from having just one damage instance; what was the design problem we were solving there?

**Comment by rosebrallier** [comment]
1. Aye from me on ballistic
2. @bleehu, halp
3. Aye
4. KILL ITTTTTT (imo)
5. Yeah, where do the "multiple hits" come from in an aesthetic sense? I'd understand specifying damage and bleed contingencies based on whether the shrapnel hits/pierces armor or not, but the whole "multiple hits" thing confuses me.
@bleehu ?

**Comment by bleehu** [comment]
1. My enemies specify that their frags are ballistic. I suggest we standardize on that.
2. Internal works for me
3. :heavy_check_mark: 
4. ayup
5. Which frags?

**Comment by Turtlelord26** [comment]
https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt#L347
https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt#L375
https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt#L407

**Comment by bleehu** [comment]
It looks like a balance/value add to armor on the arms and legs? Pretty sure that's a 1Source question.

**Comment by rosebrallier** [comment]
@1sourcecontrol Help! We'd love for you to explain these choices to us so we can make the description parse more easily.

**Comment by 1sourcecontrol** [comment]
Backstory: when I made C2.0 I was trying to bring the grenades up to more realistic damages with the rest of the weapons. I.e., 1 frag grenade turns you into a hamburger. At close range, a ESCS frag will do 135 damage if you aren't mitigating it. Tried to build the aesthetic of a fragmentation device: the frag grenades (and the portable flack cannon) do damage to 2 or 3 parts of the body (depending on the distance). So they are easily mitigated by wearing appropriate armor or you d1e.

1. Yes, frags were supposed to be ballistic.
2. The idea was: Breathing -- take full damage. Gas mask breathing -- take no damage. However that turns out in the current rules.
3. When I wrote plasma stuff, there wasn't a "plasma" damage type, per se. Plasma weapons were basically a specialized ballistic that had higher armor piercing and gave the target plasma burn (and the 2 corresponding effects: DoT and reducing the armor's piercing resistance)
4. The funny thing is, does concussive damage make you think of heat burns from the expanding gases? It makes me think of a sledgehammer. A firebomb (napalm/or really, deflagration explosives) is not necessarily a concussive weapon (brisance), while it is probably classified as an explosive. Thinking of a explosive weapons in real life specifically labeled as "concussive" -- there's an emphasis on the weapons purpose (especially high brisance, i'd imagine).
5. Lol have you guys not used frags much since C2.0 was released? Man, I never got to play C2.0 or there would be grenades everywhere :( Design problem was the incredible effectiveness of frag grenades and making grenades have noticeably different mechanics to give more strategy.

How I see it, throw the grenade - roll to hit, success - take 45x2 or 3 damage, blocking each chunk with armor or taking the damage straight.

**Comment by Turtlelord26** [comment]
Thanks!

Unfortunately, this style of grenade damage isn't going to work well with static armor. If I toss a grenade into a group of 4 targets, and those targets have static armor values, who rolls what to see if the nade hits them or their armor? Do I, as the attacker, 
* roll acc on each on them after rolling acc to throw in the first place (unrealistic and too many dice), 
* roll acc once after already rolling to throw it (doesn't take into account different circumstances of different targets *relative to the grenade* very well), 
* just use the one acc roll (flavor concerns, a badly thrown grenade still hurts like a truck), or 
* have the targets each roll ... some special armor roll used only for AoE?

We might want to consider a modified DnD-style protocol with AOE damage being mitigated by a save and/or by positional cover instead of an accuracy-armor contest (and I would strongly consider making area damage always hit armor if relevant damage type). Naturally, we don't need to start working on any such thing until static armor gets going, but I'm sneaking the thoughts into your heads in advance. 🐢

**Comment by Turtlelord26** [comment]
574 addresses points 1 through 4 but not 5.

**Comment by rosebrallier** [comment]
@Turtlelord26 What fixes do we still need to implement here?

**Comment by Turtlelord26** [comment]
We still need to address the complexity of the damage grenades and how they interact with armor, which is blocked by the Static Armor project.
