### ISSUE TITLE
Gripe: Burst/Autofiring Accuracy Stacking

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#510]
The current proposed version of Expertise - Assault Rifle can combine with some lower rail attachments to make burstfire more accurate than semi-auto fire. This is, of course, wrong.

At the moment, it seems most reasonable to change the lower rail attachment to increase semi-auto accuracy as well as burst/auto, though redesigning assault rife expertise is also possible.

**Comment by bleehu** [comment]
Lovin' the new Gripe label!

**Comment by bleehu** [comment]
If we let foregrip increase single fire accuracy as well, we run into one of the issues that 1Source was trying to avoid, which was being so accurate that you can hit targets hunkered in cover. 

Posting a link to the attachments in question for ease of navigation. https://github.com/bleehu/Compound_X/blob/dev/Items/04_00_WeaponAttachments.txt#L353
https://github.com/bleehu/Compound_X/blob/dev/Items/04_00_WeaponAttachments.txt#L346

**Comment by Turtlelord26** [comment]
I hear that. I think I will try to find a replacement for that particular expertise bonus.

In that case, we should make a formal design note somewhere that only lower rail attachments are allowed to make specifically burst- and/or autofire more accurate.

**Comment by 1sourcecontrol** [comment]
>make burstfire more accurate than semi-auto fire. This is, of course, wrong.

I believe this problem is already taken care of. When reworking all the weapons I was worried about all the possibilities so I made a hard-stop for auto-burst miss chances:

https://github.com/bleehu/Compound_X/blob/fa4df08b463211cf320d4d9bfd5e0b89524544a4/01_02_Combat_Rules.txt#L10
	At any time when using a melee or ranged weapon, you have a minimum of -2 
weapon miss chance, and a minimum of 1 Auto or Burst miss chance (if relevant). 
These minimums apply after all PER/DEX/STR/Attachment modifiers, at all ranges, 
and before cover and any other environmental effects. Using an ability could 
push you below the minimum miss chance.

**Comment by 1sourcecontrol** [comment]
In case my rule wording isn't clear... let's say you have a 1 miss chance with semi, then the most accurate you can be with auto/burst is a 2 miss chance.

**Comment by Turtlelord26** [comment]
That was unclear. I've thought all along that you hard-stopped semi-auto acc at -2 and also, separately, hard-stopped burst- and autofire at 1. I'm going to go ahead a PR a wording update to that section (I think adding the word 'modifier' after 'Auto or Burst miss chance').

But in the long run, I prefer our systems be elegant enough that you have to work at it to run into one of the hard stops, where possible.

**Comment by 1sourcecontrol** [comment]
I see what you mean. When I wrote C2.0 I tried to design all auto/burst miss chance as a modifier.

>But in the long run, I prefer our systems be elegant enough that you have to work at it to run into one of the hard stops, where possible.

Definitely what I prefer. After all, I don't want to just add another rule to the rule book. But I counted the cost and thought it would be too difficult to run increasing permutations on every new or existing way to reduce miss chance (feats/attachments/class/class choices/race). 
But is it really a question of elegance or design choice? By giving the player tons of options to be effective with weapons, they have many player progressions to fulfill the same goal. A min-max player could -likely- abuse the system to get incredible accuracy. The hard-stop prevents that -- if not the hard stop, some other rule may have to be added. If you'd rather reduce the ranges of all components so that a hardstop is never needed -- that differs in design choice for weapon progression. Anyways, just some thoughts on it.

**Comment by Turtlelord26** [comment]
Addressed in #542, this can close once that PR merges.

Being clear, I don't want to nix the hard-stop. My attitude towards it is that I would rather have it and not need it than need it and not have it. And the balance question becomes a lot simpler if we make the design call to restrict the only kinds of bonuses that can break this particular hard stop to exactly one subset of attachments.
