### ISSUE TITLE
A miss that crits?

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#52]
Possible to run a dualwield smg build that crits on 61% but misses above 70 (with no attachments, spray and pray x3, dual wield not akimbo,) which is true, does it auto hit because of crit, or does it miss?

**Comment by bleehu** [comment]
The critical effect as described in the basic rules:
https://github.com/trowl223/Compound_X/blob/play/play/PlayerRules/Basic%20Rules.txt#L273
only affects damage. Since you only do damage if you hit, rolling a 65 would critically hit the wall behind the target. 
How are you getting critical hits on 61%?

**Comment by Wildlovelies** [comment]
luck at 10 plus double tap

**Comment by bleehu** [comment]
Maybe we shouldn't use Luck Modifier in crit rolls. I think that the scaling is off on the high end.
https://github.com/trowl223/Compound_X/blob/play/play/PlayerRules/Basic%20Rules.txt#L275
And maybe nerf Double Tap to + 8%?
https://github.com/trowl223/Compound_X/blob/play/play/PlayerRules/Basic%20Rules.txt#L275

Keeping in mind that stealth attacks still might add a +10% to crit. These nerfs would also curb several other crit builds, but wouldn't destroy them entirely.

What do you think @trowl223 ?

**Comment by Wildlovelies** [comment]
well then you are depreciating luck to a point that it will most likely return to dump stat on most characters

**Comment by Wildlovelies** [comment]
it makes 10 luck similar effect to 10 strength or dex. it is a specialization

**Comment by Wildlovelies** [comment]
difference between 10 luck and strength / dex, is it has significantly less secondary effects, 10 str can rip turrets off or carry a person, 10 dex has 10 movement, 10 luck only helps on luck rolls, which are far fewer, than say reflex rolls, athletics or acrobatics...

**Comment by 1sourcecontrol** [comment]
@bleehu you could nerf it to ((Luck-5)*3) or ((Luck-5)*2).
Also, since crits don't have a very significant effect on damage, I think the main thing that changes is the viability of crit builds. 
It might be good to come up with some more benefits to having luck, as lovelies mentioned, if crits are decoupled from luck.

**Comment by Wildlovelies** [comment]
we can close this
