### ISSUE TITLE
Luck critical modifier too powerful

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#56]
It has been brought up luck modifies crits to too high a number, removing crits from luck removes the stat mostly from gameplay, so I propose a middle ground.

Let luck modifier be determined by a *2 instead of *4, let it still modify crits, (10% at lvl 10) then crits are still affected negatively as well by dumping the stat,  but I also proposed we let it add to either reflex or initiative. If you build your character unlucky, they go first less in combat, on the contrary, a lucky person might go first more, but again this modifier would be a bonus of 10 at 10 luck, still under the soldier bonus. and could stack with the soldier bonus.

**Comment by trowl223** [comment]
Initiative would make more sense from a mechanics point of view, but not from a logical one. In my opinion this idea should be tested, I believe it would add usefulness to a stat and make an area of the game more dynamic.

**Comment by bleehu** [comment]
The branch was merged before the change could be made. @1sourcecontrol could you finish up this change and we'll merge it again?

**Comment by 1sourcecontrol** [comment]
Per our conversation, @bleehu, I propose that we close this issue. I think we should leave crits the way they are, for now. I see a lot less potential for abuse now that nanite-regen is being redone and automatic weapons can't crit.

**Comment by bleehu** [comment]
I think we should make a cap that says you can't increase crit range beyond a roll of 80+ even in the case of temporary luck, etc. I think Wildlovelies could still abuse crits.

**Comment by 1sourcecontrol** [comment]
Why don't we have lovelies try?
My thoughts:
There are two ways, that I know of, that could possibly abuse crits.
1. Criticals cause bonus damage.
               Even if a player got 100% extra-crit on every roll, which is +20 damage constantly, he can't use it during automatic fire. It matters for beating armor DR, so they would be better at dealing with high armor targets; however, the virtual double or triple damage automatic fire can get compared to +20-60% damage, that could be attained by single-fire 100%-crit, makes criticals far more insignificant, imo, for higher HP targets or targets with less than 100% armor coverage.
2. Critical's interactions with other abilities and feats.
               Side note, I haven't studied every ability in the game, mostly engineer and medic, so I can't say for sure (plus my class is Human and I make mistakes lol) but here are all the interactions I know of: Double Tap, First Shot Counts, and Nanite Regen. (I left out Never Tell Me the Odds because it just adds to crit chance).

Double Tap, double damage on all hits would be a major concern, but the player's apples to apples DPS would still be much lower than an automatic weapon. Fortunately, double damage only occurs in extra crit range, which can be maxed out somewhere around 25% chance (10% from LUCK mod + 5% base chance, 5% weapon skill trees, 5% other feat) with the current abilities and using a single fire carbine, I believe.

First Shot Counts: +20 damage every time you reload looks like a below average feat to take, to me (even if you had 100% chance of crit'ing). The only abuse I could see is a single shot break-barrel shotgun, always getting a crit. And frankly, since the shotgun gets far less DPS than a 30rnd mag automatic weapon, I think it nullifies the concern.

Nanite Regen: getting balanced. Since you can't crit with an automatic weapon, half the battle is already won (maybe the whole battle). Make it so nanite regen steals from the pool of the target, and then you have a hard cap on max regeneration from a single target. Another possibility is to limit it to a certain number of procs per turn. There are a lot of options for dealing with this feat.

__Final thought__ , as I'm sure you all know, what may be a key decider in determining whether having a high crit range is balanced is to compare what the player has to give up. Giving up 2-3 feats and 40 skill points (weapon skill trees), and maxing LUCK to get maximum crit chance is a high price.

**Comment by trowl223** [comment]
I agree with what @1sourcecontrol has brought up. Recent changes (especially the automatic fire negating crits) have drastically lowered the possibility for abuse of the crit system.

I do believe that he has also brought to light that First shot counts (and Last shot counts) could use some buffing, as they add 20 damage on 10% of reloads. I'm going to create a separate issue for that so we can debate it there and not fill this thread up.

**Comment by bleehu** [comment]
I still think the *4 multiplier is a bit high, but let's see how it plays out in the next versions. Closing it out =)

**Comment by 1sourcecontrol** [comment]
Thanks Mike, I'm sure we'll find out how it works, soon enough.
