### ISSUE TITLE
Game breaking builds

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#58]
Several of these have repeating themes but here is a quick list of builds that break the game as far as I can tell:
Since Cyborg is the most flexible and easy to break race, Assume all of these are Cyborg.

-Berserker: lvl 3 13 str, full armor plus 10 dr from passives, only thing they spend money on is their weapon and armor at this point so they can afford the first additional cyborg upgrade price of $2000. add power fist, you are doing 143 dmg per hit, you have 50 dr 100% coverage, and at lvl 5 any dmg you do take just increases your melee dmg even more. Add dual wield or akimbo... 

-Marksman: both builds can be broken, tech rounds with machine gun pistols and nanite regen..
Multi pin at lvl 10 is scary as hell, pick up to 13+ targets, everytime they do anything you get to shoot them.

-it'll heal soldier plus full armor: up to 50dr 100% coverage, plus only taking half dmg for everything else... 

-Nanite regen medic / engineer: ask nate...

-Adept tank build, as it stands, adept can reach 60dr plus nanite shielding, also nanite regen plus nanite shielding = near infinite effective hp.

-gunslinger machine gun pistol build with +40 dmg to pistols...

This is just glancing at the list.

**Comment by trowl223** [comment]
-Berserker: Agreed. I've never thought that a class should grant the character extra stat points. Players should build their character for the class, not the other way around.
-Marksman: Add text to class abilities that they can only be used on long rifles. Additionally for pin feat, note that reacting to a pinned enemy can only be used a certain number of times per round, maybe level/4 rounding up?
-Soldier: Probably can have a look taken at it from a new point of view.
-Medic: Nerf? I feel that a lot of medic abilities are not balanced.
-Adept: Nanite shields don't work that way. Nanite shields have a separate pool that only works as a health pool. I realize this is stated nowhere, for future reference this is their intention. The health pool would not be regenerated by any abilities as it is in a closed system.
-Gunslinger: You failed to mention that this is by level 8. Additionally the same can be said for every class that uses SMGs (Only Soldiers, Doctors, Priests, Pilots, Adepts and Paladins), +3 rounds per half action of firing doubles their max rate of fire, doubling damage. The +30% miss chance is countered by more availability on an SMG to reduce that miss chance with upgrades. Gunslingers also have much less mag space (partially due to armour restrictions), meaning that on average they will cease to be of use in a fight in half the time of anyone with an SMG.

**Comment by 1sourcecontrol** [comment]
@Wildlovelies please add the rest of your list so it's addressable, if possible.

@trowl223 -Gunslinger, I'd like to mention that most NPCs don't take more than a few bullets to drop. Even with reduced damage from an SMG, 6 bullets is a pretty reasonable number for a kill. 6 bullets per NPC, let's say a 6 mag limit w/ 12 round mags, that makes potentially 12 kills. 
I almost exclusively run battle rifles w/ 20 round mags, To my knowledge, I've only had to reload once in a mission in the last year of play, I usually have 8-12 rounds left in a magazine by mission end.
My point is, the ammo limitations would only matter if they wasted 50%+ of their damage potential (and had enough combat turns to do so).

**Comment by bleehu** [comment]
There's a lot of good stuff going on here, can we break this up per build so we can tackle each break individually?

**Comment by Wildlovelies** [comment]
with current pulls from play, this list as of right now is my op list, I do not have any other builds at this time.

**Comment by bleehu** [comment]
Can we break the existing list into one issue per build so that we can kill them one by one? Even if there isn't any new builds? Because there isn't one fix we can make to cure all of these. That way we can use issues to track work that still needs to be done.

**Comment by Wildlovelies** [comment]
Sure, do you want me to group similar issues, like nanite regen crit builds together?

**Comment by trowl223** [comment]
@1sourcecontrol I wish there were a way to force combat to require more rounds spent ;P

**Comment by bleehu** [comment]
We'll tackle these builds each on their own. Great work, @Wildlovelies !
