### ISSUE TITLE
Morph new Character Walkthrough into Character Creation Rules doc

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#607]
As per our design meeting on Tuesday, we need to explicitly state in our species doc that each character gets to pick 2 racial bonuses from the pool of traits from their species and subspecies.

**Comment by bleehu** [comment]
So... We don't actually state in any of the rules that you should pick a Species at all for your character... Also, we have multiple species documents, some of which don't have filetypes. Should we put character creation in Basic Rules? Or make a separate Character Creation document? Or morph the first time player guide into a character creation rule page? What was our final verdict on whether or not to split up the Species docs or keep then unified as one?

**Comment by Turtlelord26** [comment]
I like morphing the new player walkthrough into a character creation rules doc and alluding to it as such from basic rules. I bet we can keep all the new player elements (and label them as such so that the experienced know what they can skip) without compromising either objective.

I think we decided to keep each species as its own doc. At least, I prefer that.

**Comment by rosebrallier** [comment]
Perhaps a quick list of available species in character creation, with the full text in separate files?

**Comment by bleehu** [comment]
This was broken up into PRs #821 #823 #824 and a PR yet to be made

**Comment by Turtlelord26** [comment]
#698 accomplished the core issues of this ... issue. Close it out, @bleehu?
